var upcoming = [
  {
    adult: false,
    backdrop_path: "/k1KrbaCMACQiq7EA0Yhw3bdzMv7.jpg",
    genre_ids: [16, 10751, 10402, 14, 35],
    id: 901362,
    original_language: "en",
    original_title: "Trolls Band Together",
    overview:
      "When Branch's brother, Floyd, is kidnapped for his musical talents by a pair of nefarious pop-star villains, Branch and Poppy embark on a harrowing and emotional journey to reunite the other brothers and rescue Floyd from a fate even worse than pop-culture obscurity.",
    popularity: 920.108,
    poster_path: "/bkpPTZUdq31UGDovmszsg2CchiI.jpg",
    release_date: "2023-10-12",
    title: "Trolls Band Together",
    video: false,
    vote_average: 7.2,
    vote_count: 380,
  },
  {
    adult: false,
    backdrop_path: "/aNG1BSIULxbHtUmBiar0i3fR1S4.jpg",
    genre_ids: [16, 12, 35, 10751],
    id: 520758,
    original_language: "en",
    original_title: "Chicken Run: Dawn of the Nugget",
    overview:
      "A band of fearless chickens flock together to save poultry-kind from an unsettling new threat: a nearby farm that's cooking up something suspicious.",
    popularity: 383.198,
    poster_path: "/exNtEY8QUuQh9e23wSQjkPxKIU3.jpg",
    release_date: "2023-12-08",
    title: "Chicken Run: Dawn of the Nugget",
    video: false,
    vote_average: 7.627,
    vote_count: 126,
  },
  {
    adult: false,
    backdrop_path: "/bckxSN9ueOgm0gJpVJmPQrecWul.jpg",
    genre_ids: [28, 12, 14],
    id: 572802,
    original_language: "en",
    original_title: "Aquaman and the Lost Kingdom",
    overview:
      "Black Manta, still driven by the need to avenge his father's death and wielding the power of the mythic Black Trident, will stop at nothing to take Aquaman down once and for all. To defeat him, Aquaman must turn to his imprisoned brother Orm, the former King of Atlantis, to forge an unlikely alliance in order to save the world from irreversible destruction.",
    popularity: 522.991,
    poster_path: "/e71ZaR31LYhJZFUqMz309fbM8ZB.jpg",
    release_date: "2023-12-20",
    title: "Aquaman and the Lost Kingdom",
    video: false,
    vote_average: 8.5,
    vote_count: 18,
  },
  {
    adult: false,
    backdrop_path: "/bWIIWhnaoWx3FTVXv6GkYDv3djL.jpg",
    genre_ids: [878, 27, 28],
    id: 940721,
    original_language: "ja",
    original_title: "ゴジラ-1.0",
    overview:
      "In postwar Japan, a new terror rises. Will the devastated people be able to survive... let alone fight back?",
    popularity: 439.588,
    poster_path: "/hkxxMIGaiCTmrEArK7J56JTKUlB.jpg",
    release_date: "2023-11-03",
    title: "Godzilla Minus One",
    video: false,
    vote_average: 8.058,
    vote_count: 147,
  },
  {
    adult: false,
    backdrop_path: "/ptz5ETMxDoRRiE69BVuIxJzyTEO.jpg",
    genre_ids: [16, 35, 12, 10751],
    id: 940551,
    original_language: "en",
    original_title: "Migration",
    overview:
      "After a migrating duck family alights on their pond with thrilling tales of far-flung places, the Mallard family embarks on a family road trip, via New York City, to tropical Jamaica.",
    popularity: 323.777,
    poster_path: "/ldfCF9RhR40mppkzmftxapaHeTo.jpg",
    release_date: "2023-12-06",
    title: "Migration",
    video: false,
    vote_average: 7.6,
    vote_count: 31,
  },
  {
    adult: false,
    backdrop_path: "/ehumsuIBbgAe1hg343oszCLrAfI.jpg",
    genre_ids: [16, 10751, 14, 12],
    id: 1022796,
    original_language: "en",
    original_title: "Wish",
    overview:
      "Asha, a sharp-witted idealist, makes a wish so powerful that it is answered by a cosmic force – a little ball of boundless energy called Star. Together, Asha and Star confront a most formidable foe - the ruler of Rosas, King Magnifico - to save her community and prove that when the will of one courageous human connects with the magic of the stars, wondrous things can happen.",
    popularity: 280.638,
    poster_path: "/AcoVfiv1rrWOmAdpnAMnM56ki19.jpg",
    release_date: "2023-11-13",
    title: "Wish",
    video: false,
    vote_average: 6.664,
    vote_count: 122,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [99],
    id: 1192578,
    original_language: "es",
    original_title: "Elijo creer",
    overview:
      "It narrates the epic title obtained by the Argentine National Team in the World Cup Qatar 2022 with testimonies of the protagonists, told from the intimacy and in first person.",
    popularity: 266.959,
    poster_path: "/tAX05FIcjnllogMa2r0FmamNhpU.jpg",
    release_date: "2023-12-07",
    title: "Soccer Soul",
    video: false,
    vote_average: 7,
    vote_count: 2,
  },
  {
    adult: false,
    backdrop_path: "/pA3vdhadJPxF5GA1uo8OPTiNQDT.jpg",
    genre_ids: [28, 18],
    id: 678512,
    original_language: "en",
    original_title: "Sound of Freedom",
    overview:
      "The story of Tim Ballard, a former US government agent, who quits his job in order to devote his life to rescuing children from global sex traffickers.",
    popularity: 230.581,
    poster_path: "/qA5kPYZA7FkVvqcEfJRoOy4kpHg.jpg",
    release_date: "2023-07-03",
    title: "Sound of Freedom",
    video: false,
    vote_average: 8.083,
    vote_count: 1609,
  },
  {
    adult: false,
    backdrop_path: "/8RBwd37p2p48lUmZuWBLSkFLprd.jpg",
    genre_ids: [27, 53, 35],
    id: 1113278,
    original_language: "en",
    original_title: "It's a Wonderful Knife",
    overview:
      "Winnie's life is less than wonderful one year after saving her town from a psychotic killer on Christmas Eve. When she wishes she was never born, she finds herself magically transported to a nightmarish parallel universe. With the murderous maniac now back, she must team up with a misfit to identify the culprit and get back to her own reality.",
    popularity: 205.348,
    poster_path: "/bnm5NntrQBcG3P7DbO00v2FmXm8.jpg",
    release_date: "2023-11-10",
    title: "It's a Wonderful Knife",
    video: false,
    vote_average: 5.3,
    vote_count: 36,
  },
  {
    adult: false,
    backdrop_path: "/iEFuHjqrE059SmflBva1JzDJutE.jpg",
    genre_ids: [16, 14, 28, 10749, 10751],
    id: 496450,
    original_language: "fr",
    original_title: "Miraculous - le film",
    overview:
      "A life of an ordinary Parisian teenager Marinette goes superhuman when she becomes Ladybug. Bestowed with magical powers of creation, Ladybug must unite with her opposite, Cat Noir, to save Paris as a new villain unleashes chaos unto the city.",
    popularity: 162.296,
    poster_path: "/dQNJ8SdCMn3zWwHzzQD2xrphR1X.jpg",
    release_date: "2023-07-05",
    title: "Miraculous: Ladybug & Cat Noir, The Movie",
    video: false,
    vote_average: 7.791,
    vote_count: 688,
  },
  {
    adult: false,
    backdrop_path: "/qElNES0sHVQcbzvGrTx7ccpGzij.jpg",
    genre_ids: [878, 28, 18],
    id: 842675,
    original_language: "zh",
    original_title: "流浪地球2",
    overview:
      "Humans built huge engines on the surface of the earth to find a new home. But the road to the universe is perilous. In order to save earth, young people once again have to step forward to start a race against time for life and death.",
    popularity: 140.589,
    poster_path: "/pR858ihc6Ls9xohpdRJVjV787ml.jpg",
    release_date: "2023-01-22",
    title: "The Wandering Earth II",
    video: false,
    vote_average: 7.249,
    vote_count: 411,
  },
  {
    adult: false,
    backdrop_path: "/gsVC7HMf4VR2XFOyqjTSklY2Tms.jpg",
    genre_ids: [878, 35, 14, 18],
    id: 792307,
    original_language: "en",
    original_title: "Poor Things",
    overview:
      "Brought back to life by an unorthodox scientist, a young woman runs off with a debauched lawyer on a whirlwind adventure across the continents. Free from the prejudices of her times, she grows steadfast in her purpose to stand for equality and liberation.",
    popularity: 134.07,
    poster_path: "/jG4o67eZKlvuL5R6WTysRkPwE75.jpg",
    release_date: "2023-12-07",
    title: "Poor Things",
    video: false,
    vote_average: 9,
    vote_count: 12,
  },
  {
    adult: false,
    backdrop_path: "/50stq3Jlny6oEgJjsXbQvbajCNw.jpg",
    genre_ids: [18, 10749],
    id: 1020006,
    original_language: "en",
    original_title: "Priscilla",
    overview:
      "When teenage Priscilla Beaulieu meets Elvis Presley at a party, the man who is already a meteoric rock-and-roll superstar becomes someone entirely unexpected in private moments: a thrilling crush, an ally in loneliness, a vulnerable best friend.",
    popularity: 130.201,
    poster_path: "/uDCeELWWpsNq7ErM61Yuq70WAE9.jpg",
    release_date: "2023-10-27",
    title: "Priscilla",
    video: false,
    vote_average: 7.2,
    vote_count: 63,
  },
  {
    adult: false,
    backdrop_path: "/ktHEdqmMWC1wdfPRMRCTZe2OISL.jpg",
    genre_ids: [27, 53, 9648],
    id: 1071215,
    original_language: "en",
    original_title: "Thanksgiving",
    overview:
      "After a Black Friday riot ends in tragedy, a mysterious Thanksgiving-inspired killer terrorizes Plymouth, Massachusetts - the birthplace of the holiday. Picking off residents one by one, what begins as random revenge killings are soon revealed to be part of a larger, sinister holiday plan.",
    popularity: 130.127,
    poster_path: "/f5f3TEVst1nHHyqgn7Z3tlwnBIH.jpg",
    release_date: "2023-11-16",
    title: "Thanksgiving",
    video: false,
    vote_average: 6.4,
    vote_count: 112,
  },
  {
    adult: false,
    backdrop_path: "/gg4zZoTggZmpAQ32qIrP5dtnkEZ.jpg",
    genre_ids: [28, 80],
    id: 891699,
    original_language: "en",
    original_title: "Silent Night",
    overview:
      "A tormented father witnesses his young son die when caught in a gang's crossfire on Christmas Eve. While recovering from a wound that costs him his voice, he makes vengeance his life's mission and embarks on a punishing training regimen in order to avenge his son's death.",
    popularity: 126.164,
    poster_path: "/tlcuhdNMKNGEVpGqBZrAaOOf1A6.jpg",
    release_date: "2023-11-30",
    title: "Silent Night",
    video: false,
    vote_average: 6.677,
    vote_count: 48,
  },
  {
    adult: false,
    backdrop_path: "/sQLMaESdeELB7Dl8HdxfGlZYRzu.jpg",
    genre_ids: [35, 18],
    id: 840430,
    original_language: "en",
    original_title: "The Holdovers",
    overview:
      "A curmudgeonly instructor at a New England prep school is forced to remain on campus during Christmas break to babysit the handful of students with nowhere to go. Eventually, he forms an unlikely bond with one of them — a damaged, brainy troublemaker — and with the school’s head cook, who has just lost a son in Vietnam.",
    popularity: 125.425,
    poster_path: "/VHSzNBTwxV8vh7wylo7O9CLdac.jpg",
    release_date: "2023-10-27",
    title: "The Holdovers",
    video: false,
    vote_average: 7.7,
    vote_count: 164,
  },
  {
    adult: false,
    backdrop_path: "/97MOhHIgU6ZdLcB9DrAhx3WAqrU.jpg",
    genre_ids: [18, 35],
    id: 839369,
    original_language: "en",
    original_title: "May December",
    overview:
      "Twenty years after their notorious tabloid romance gripped the nation, a married couple buckles under pressure when an actress arrives to do research for a film about their past.",
    popularity: 125.299,
    poster_path: "/yibtHDMO70RueiEmtrcJeTiiHFo.jpg",
    release_date: "2023-11-16",
    title: "May December",
    video: false,
    vote_average: 6.826,
    vote_count: 115,
  },
  {
    adult: false,
    backdrop_path: "/jBOyi3ibJbVa1imTCcddPUxTVAV.jpg",
    genre_ids: [35, 27, 14],
    id: 956920,
    original_language: "no",
    original_title: "There's Something in the Barn",
    overview:
      "An American family fulfills their dream of moving back to their roots after inheriting a remote cabin in the mountains of Norway. But there's a surprise waiting for them.",
    popularity: 123.409,
    poster_path: "/axrzMJR5VPWYNiW9ArENiMEPTjr.jpg",
    release_date: "2023-11-02",
    title: "There's Something in the Barn",
    video: false,
    vote_average: 7.3,
    vote_count: 51,
  },
  {
    adult: false,
    backdrop_path: "/a0GM57AnJtNi7lMOCamniiyV10W.jpg",
    genre_ids: [16, 12, 14, 18],
    id: 508883,
    original_language: "ja",
    original_title: "君たちはどう生きるか",
    overview:
      "While the Second World War rages, the teenage Mahito, haunted by his mother's tragic death, is relocated from Tokyo to the serene rural home of his new stepmother Natsuko, a woman who bears a striking resemblance to the boy's mother. As he tries to adjust, this strange new world grows even stranger following the appearance of a persistent gray heron, who perplexes and bedevils Mahito, dubbing him the \"long-awaited one.\"",
    popularity: 122.123,
    poster_path: "/jDQPkgzerGophKRRn7MKm071vCU.jpg",
    release_date: "2023-07-14",
    title: "The Boy and the Heron",
    video: false,
    vote_average: 7.3,
    vote_count: 278,
  },
  {
    adult: false,
    backdrop_path: "/A1g8AvP3KpDyu0iyjS6roRxK77v.jpg",
    genre_ids: [53, 80],
    id: 978870,
    original_language: "it",
    original_title: "L'ultima notte di Amore",
    overview:
      "On the night before his retirement, police lieutenant Franco Amore is called to investigate the death of a long-time partner of his in a diamond heist in which he was involved.",
    popularity: 105.97,
    poster_path: "/dBp0REsZkZ1HK1PycwlLdBtYdsd.jpg",
    release_date: "2023-03-09",
    title: "Last Night of Amore",
    video: false,
    vote_average: 7.245,
    vote_count: 320,
  },
  {
    adult: false,
    backdrop_path: "/nlPCdZlHtRNcF6C9hzUH4ebmV1w.jpg",
    genre_ids: [35, 18, 10749, 10402],
    id: 313369,
    original_language: "en",
    original_title: "La La Land",
    overview:
      "Mia, an aspiring actress, serves lattes to movie stars in between auditions and Sebastian, a jazz musician, scrapes by playing cocktail party gigs in dingy bars, but as success mounts they are faced with decisions that begin to fray the fragile fabric of their love affair, and the dreams they worked so hard to maintain in each other threaten to rip them apart.",
    popularity: 104.44,
    poster_path: "/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
    release_date: "2016-11-29",
    title: "La La Land",
    video: false,
    vote_average: 7.9,
    vote_count: 15785,
  },
  {
    adult: false,
    backdrop_path: "/pcRCkUtOJ1HSHJ9ZU5mOZ3zpboI.jpg",
    genre_ids: [18, 36],
    id: 906126,
    original_language: "es",
    original_title: "La sociedad de la nieve",
    overview:
      "On October 13, 1972, Uruguayan Air Force Flight 571, chartered to take a rugby team to Chile, crashes into a glacier in the heart of the Andes.",
    popularity: 85.733,
    poster_path: "/k7rEpZfNPB35FFHB00ZhXHKTL7X.jpg",
    release_date: "2023-12-15",
    title: "Society of the Snow",
    video: false,
    vote_average: 7.8,
    vote_count: 4,
  },
  {
    adult: false,
    backdrop_path: "/3YPP5Buu2lWyRU2YTYRtSqJikWc.jpg",
    genre_ids: [18, 10751, 14],
    id: 1092329,
    original_language: "en",
    original_title: "Journey to Bethlehem",
    overview:
      "A young woman carrying an unimaginable responsibility. A young man torn between love and honor. A jealous king who will stop at nothing to keep his crown.",
    popularity: 83.987,
    poster_path: "/cJgF1vjiNoRAh5UePmiPfjrw6Iv.jpg",
    release_date: "2023-11-09",
    title: "Journey to Bethlehem",
    video: false,
    vote_average: 7.1,
    vote_count: 8,
  },
  {
    adult: false,
    backdrop_path: "/rron9HAuS9s7zBF8iCX1tsafxUo.jpg",
    genre_ids: [18, 10749],
    id: 666277,
    original_language: "en",
    original_title: "Past Lives",
    overview:
      "Nora and Hae Sung, two childhood friends, are reunited in New York for one fateful week as they confront notions of destiny, love, and the choices that make a life.",
    popularity: 81.494,
    poster_path: "/k3waqVXSnvCZWfJYNtdamTgTtTA.jpg",
    release_date: "2023-06-02",
    title: "Past Lives",
    video: false,
    vote_average: 7.903,
    vote_count: 376,
  },
  {
    adult: false,
    backdrop_path: "/hsdwzxdX7oHWa7SX4dMAMuq2RqJ.jpg",
    genre_ids: [18, 36],
    id: 365620,
    original_language: "en",
    original_title: "Ferrari",
    overview:
      "A biopic of automotive mogul Enzo Ferrari, whose family redefined the idea of the high-powered Italian sports car and practically spawned the concept of Formula One racing.",
    popularity: 79.453,
    poster_path: "/dAP9QTLVvglGvtsa0VesaOgHcTW.jpg",
    release_date: "2023-12-14",
    title: "Ferrari",
    video: false,
    vote_average: 7.098,
    vote_count: 46,
  },
  {
    adult: false,
    backdrop_path: "/1PkBhxXdEejw8c5BC7T3cN7jz9g.jpg",
    genre_ids: [35, 10749],
    id: 1072790,
    original_language: "en",
    original_title: "Anyone But You",
    overview:
      "After an amazing first date, Bea and Ben's fiery attraction turns ice cold - until they find themselves unexpectedly reunited at a destination wedding in Australia. So they do what any two mature adults would do: pretend to be a couple.",
    popularity: 78.966,
    poster_path: "/yRt7MGBElkLQOYRvLTT1b3B1rcp.jpg",
    release_date: "2023-12-21",
    title: "Anyone But You",
    video: false,
    vote_average: 9.5,
    vote_count: 3,
  },
  {
    adult: false,
    backdrop_path: "/lr2kcIbCgP7Q06DV5Hfs3J6yuJy.jpg",
    genre_ids: [12, 28],
    id: 845111,
    original_language: "fr",
    original_title: "Les trois mousquetaires : Milady",
    overview:
      "The second of a two-part film adaptation of Alexandre Dumas' novel. Constance is kidnapped before D'Artagnan's eyes. In a frantic quest to save her, the young musketeer is forced to join forces with the mysterious Milady de Winter. But as war is declared and Athos, Porthos and Aramis have already joined the front, a terrible secret from the past shatters all old alliances. As the King falls further and further under the control of Cardinal Richelieu, D'Artagnan and the Musketeers are the last bastions before chaos. But, drawn into a plot that threatens to put the country to fire and sword, fate presents them with a terrible choice: will they have to sacrifice those they love to complete their mission?",
    popularity: 78.323,
    poster_path: "/2g3BSuUFsa88SgeMP7tlv9x92Mz.jpg",
    release_date: "2023-12-13",
    title: "The Three Musketeers: Milady",
    video: false,
    vote_average: 6.8,
    vote_count: 55,
  },
  {
    adult: false,
    backdrop_path: "/uJwTRJxMnZcnDTyesNyeZhkHaOp.jpg",
    genre_ids: [35, 18],
    id: 621587,
    original_language: "en",
    original_title: "Next Goal Wins",
    overview:
      "Dutch coach Thomas Rongen attempts the nearly impossible task of turning the American Samoa soccer team from perennial losers into winners.",
    popularity: 77.169,
    poster_path: "/zWmKqcox4AgM3deEEVCeYqEOOJ2.jpg",
    release_date: "2023-11-16",
    title: "Next Goal Wins",
    video: false,
    vote_average: 6.306,
    vote_count: 18,
  },
  {
    adult: false,
    backdrop_path: "/bP9h1qHuFQIDERuGXt43Q3TfBdg.jpg",
    genre_ids: [27],
    id: 1146143,
    original_language: "en",
    original_title: "The Puppetman",
    overview:
      "The Puppetman, a convicted killer on death row always maintained his innocence saying that it was an evil force controlling his body as he slaughtered his victims. Now Michal, the killer's daughter, begins to suspect that there may be some truth to her father's claim when those around her begin to die in brutal ways. She must try and break the curse of The Puppetman before all her loved ones are killed.",
    popularity: 75.309,
    poster_path: "/wEnct8jeMHYzOfm5Y6QmxD3V61t.jpg",
    release_date: "2023-12-22",
    title: "The Puppetman",
    video: false,
    vote_average: 1,
    vote_count: 1,
  },
  {
    adult: false,
    backdrop_path: "/c7MRmF3LMiBWokedmdQl3roTUv2.jpg",
    genre_ids: [53, 18],
    id: 798362,
    original_language: "en",
    original_title: "The Marsh King's Daughter",
    overview:
      "Helena, a woman living a seemingly ordinary life, hides a dark secret—her father is the infamous 'Marsh King', the man who kept her and her mother captive in the wilderness for years. After a lifetime of trying to escape her past, Helena is forced to face her demons when her father unexpectedly escapes from prison.",
    popularity: 74.199,
    poster_path: "/bcuEjrwhp5HgEUnFe5lc4xpEqzt.jpg",
    release_date: "2023-09-28",
    title: "The Marsh King's Daughter",
    video: false,
    vote_average: 6.709,
    vote_count: 55,
  },
  {
    adult: false,
    backdrop_path: "/4kmNLwmVeT3xMciSRefE6SCi2hX.jpg",
    genre_ids: [80, 18, 53],
    id: 1027073,
    original_language: "en",
    original_title: "In the Land of Saints and Sinners",
    overview:
      "In a remote Irish village, a damaged Finbar is forced to fight for redemption after a lifetime of sins, but what price is he willing to pay? In the land of saints and sinners, some sins can't be buried.",
    popularity: 67.247,
    poster_path: "/jN8JJaVpADPEU6SZX8QBCZHAFrU.jpg",
    release_date: "2023-10-06",
    title: "In the Land of Saints and Sinners",
    video: false,
    vote_average: 6.6,
    vote_count: 51,
  },
  {
    adult: false,
    backdrop_path: "/c2bUvZG7uwdM4AmH0wT8HXXKeBg.jpg",
    genre_ids: [16, 35, 12, 28],
    id: 1062807,
    original_language: "ja",
    original_title: "劇場版 SPY×FAMILY CODE: White",
    overview:
      "After receiving an order to be replaced in Operation Strix, Loid decides to help Anya win a cooking competition at Eden Academy by making the principal's favorite meal in order to prevent his replacement. The Forgers decide to travel to the region where the meal originates, but accidentally set off a chain of events which could put the world's peace at risk.",
    popularity: 67.144,
    poster_path: "/rScguiryGULl9cPmLRBSYyqotWR.jpg",
    release_date: "2023-12-22",
    title: "SPY x FAMILY CODE: White",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/xGoSJGwTK9KfVwN04F5021cPgXg.jpg",
    genre_ids: [35, 18, 10751],
    id: 11881,
    original_language: "en",
    original_title: "Miracle on 34th Street",
    overview:
      "Kris Kringle, seemingly the embodiment of Santa Claus, is asked to portray the jolly old fellow at Macy's following his performance in the Thanksgiving Day parade. His portrayal is so complete that many begin to question if he truly is Santa Claus, while others question his sanity.",
    popularity: 63.443,
    poster_path: "/qyAc9X9XHloIqy3oJbbZ44Cw0Hm.jpg",
    release_date: "1947-06-04",
    title: "Miracle on 34th Street",
    video: false,
    vote_average: 7.345,
    vote_count: 657,
  },
  {
    adult: false,
    backdrop_path: "/b1dUCCd1hi5ZfyyCCoJTmViaXM2.jpg",
    genre_ids: [18],
    id: 850165,
    original_language: "en",
    original_title: "Iron Claw",
    overview:
      "The true story of the inseparable Von Erich brothers, who made history in the intensely competitive world of professional wrestling in the early 1980s. Through tragedy and triumph, under the shadow of their domineering father and coach, the brothers seek larger-than-life immortality on the biggest stage in sports.",
    popularity: 57.06,
    poster_path: "/lsdismtCDga4vsKnmliz0h7CaZT.jpg",
    release_date: "2023-12-21",
    title: "Iron Claw",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/1i2DLQ5WlGV2LOvlwFhtbU4ElMO.jpg",
    genre_ids: [18],
    id: 558915,
    original_language: "en",
    original_title: "The Color Purple",
    overview:
      "A decades-spanning tale of love and resilience and of one woman's journey to independence. Celie faces many hardships in her life, but ultimately finds extraordinary strength and hope in the unbreakable bonds of sisterhood.",
    popularity: 54.082,
    poster_path: "/dNDc529cX53g6bmKetzAbnWGIB5.jpg",
    release_date: "2023-12-25",
    title: "The Color Purple",
    video: false,
    vote_average: 10,
    vote_count: 1,
  },
  {
    adult: false,
    backdrop_path: "/czbn0za9QyP5umRBikimxQ2iNm9.jpg",
    genre_ids: [10749, 35],
    id: 970948,
    original_language: "en",
    original_title: "What Happens Later",
    overview:
      "Two ex-lovers get snowed in at a regional airport overnight. Indefinitely delayed, Willa, a magical thinker, and Bill, a catastrophic one, find themselves just as attracted to and annoyed by one another as they did decades earlier. But as they unpack the riddle of their mutual past and compare their lives to the dreams they once shared, they begin to wonder if their reunion is mere coincidence, or something more enchanted.",
    popularity: 53.059,
    poster_path: "/5TrWftAac3EeMcatyiCdAglWKb6.jpg",
    release_date: "2023-11-02",
    title: "What Happens Later",
    video: false,
    vote_average: 5.625,
    vote_count: 12,
  },
  {
    adult: false,
    backdrop_path: "/vBxiqbzWidThhM57hgq8fZL025A.jpg",
    genre_ids: [28, 53],
    id: 927107,
    original_language: "en",
    original_title: "The Bricklayer",
    overview:
      "Someone is blackmailing the CIA by assassinating foreign journalists and making it look like the agency is responsible. As the world begins to unite against the U.S., the CIA must lure its most brilliant – and rebellious – operative out of retirement, forcing him to confront his checkered past while unraveling an international conspiracy.",
    popularity: 51.852,
    poster_path: "/5Osn4Y4Cc4VGrp3nR3VfVJWtA7l.jpg",
    release_date: "2023-12-14",
    title: "The Bricklayer",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/oeBom7DLr85lixEkWOGmhCPEfuY.jpg",
    genre_ids: [80, 18, 53],
    id: 842942,
    original_language: "en",
    original_title: "Bandit",
    overview:
      "After escaping a Michigan prison, a charming career criminal assumes a new identity in Canada and goes on to rob a record 59 banks and jewellery stores while being hunted by a rogue task force. Based on the story of The Flying Bandit.",
    popularity: 50.33,
    poster_path: "/yph9PAbmjYPvyvbeZvdYIhCZHEu.jpg",
    release_date: "2022-09-23",
    title: "Bandit",
    video: false,
    vote_average: 6.2,
    vote_count: 243,
  },
  {
    adult: false,
    backdrop_path: "/bx6ipM7K7hF6B974POq5PkbqfNc.jpg",
    genre_ids: [14, 35, 27],
    id: 823482,
    original_language: "en",
    original_title: "Dream Scenario",
    overview:
      "Hapless family man Paul Matthews finds his life turned upside down when millions of strangers suddenly start seeing him in their dreams. But when his nighttime appearances take a nightmarish turn, Paul is forced to navigate his newfound stardom.",
    popularity: 50.304,
    poster_path: "/eMaAi8wTI5wON8pp33w3BDuGyZ8.jpg",
    release_date: "2023-11-10",
    title: "Dream Scenario",
    video: false,
    vote_average: 7.459,
    vote_count: 61,
  },
];
let text = document.querySelectorAll("h6");
let img = document.querySelectorAll(".poster");
for (i = 0; i < upcoming.length; i++) {
  img[i].src = "https://image.tmdb.org/t/p/original" + upcoming[i].poster_path;
  text[i].textContent = upcoming[i].title;
}

