var upcoming = [
  {
    adult: false,
    backdrop_path: "/k1KrbaCMACQiq7EA0Yhw3bdzMv7.jpg",
    genre_ids: [16, 10751, 10402, 14, 35],
    id: 901362,
    original_language: "en",
    original_title: "Trolls Band Together",
    overview:
      "When Branch's brother, Floyd, is kidnapped for his musical talents by a pair of nefarious pop-star villains, Branch and Poppy embark on a harrowing and emotional journey to reunite the other brothers and rescue Floyd from a fate even worse than pop-culture obscurity.",
    popularity: 901.938,
    poster_path: "/sEaLO9s7CIN3fjz8R3Qksum44en.jpg",
    release_date: "2023-10-12",
    title: "Trolls Band Together",
    video: false,
    vote_average: 7.168,
    vote_count: 361,
  },
  {
    adult: false,
    backdrop_path: "/AucuqDaUW4z1oT5XyL71qwRY2F6.jpg",
    genre_ids: [27, 53],
    id: 983507,
    original_language: "no",
    original_title: "Meg, deg & Frank",
    overview:
      "Christian - a millionaire heir, meets Sigrid - a young student, on a dating app. They hit it off quickly, but there's only one problem: Christian lives with Frank, a man who dresses up and constantly acts like a dog.",
    popularity: 842.589,
    poster_path: "/9DPG1gxLwV2oyFdHq3SnISsWbse.jpg",
    release_date: "2022-06-03",
    title: "Good Boy",
    video: false,
    vote_average: 6.856,
    vote_count: 101,
  },
  {
    adult: false,
    backdrop_path: "/jXJxMcVoEuXzym3vFnjqDW4ifo6.jpg",
    genre_ids: [28, 12, 14],
    id: 572802,
    original_language: "en",
    original_title: "Aquaman and the Lost Kingdom",
    overview:
      "Black Manta, still driven by the need to avenge his father's death and wielding the power of the mythic Black Trident, will stop at nothing to take Aquaman down once and for all. To defeat him, Aquaman must turn to his imprisoned brother Orm, the former King of Atlantis, to forge an unlikely alliance in order to save the world from irreversible destruction.",
    popularity: 371.884,
    poster_path: "/8xV47NDrjdZDpkVcCFqkdHa3T0C.jpg",
    release_date: "2023-12-20",
    title: "Aquaman and the Lost Kingdom",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/bWIIWhnaoWx3FTVXv6GkYDv3djL.jpg",
    genre_ids: [878, 27, 28],
    id: 940721,
    original_language: "ja",
    original_title: "ゴジラ-1.0",
    overview:
      "In postwar Japan, a new terror rises. Will the devastated people be able to survive... let alone fight back?",
    popularity: 360.239,
    poster_path: "/hkxxMIGaiCTmrEArK7J56JTKUlB.jpg",
    release_date: "2023-11-03",
    title: "Godzilla Minus One",
    video: false,
    vote_average: 8.108,
    vote_count: 125,
  },
  {
    adult: false,
    backdrop_path: "/8RBwd37p2p48lUmZuWBLSkFLprd.jpg",
    genre_ids: [27, 53, 35],
    id: 1113278,
    original_language: "en",
    original_title: "It's a Wonderful Knife",
    overview:
      "Winnie's life is less than wonderful one year after saving her town from a psychotic killer on Christmas Eve. When she wishes she was never born, she finds herself magically transported to a nightmarish parallel universe. With the murderous maniac now back, she must team up with a misfit to identify the culprit and get back to her own reality.",
    popularity: 223.962,
    poster_path: "/bnm5NntrQBcG3P7DbO00v2FmXm8.jpg",
    release_date: "2023-11-10",
    title: "It's a Wonderful Knife",
    video: false,
    vote_average: 5.194,
    vote_count: 31,
  },
  {
    adult: false,
    backdrop_path: "/ehumsuIBbgAe1hg343oszCLrAfI.jpg",
    genre_ids: [16, 10751, 14, 12],
    id: 1022796,
    original_language: "en",
    original_title: "Wish",
    overview:
      "Asha, a sharp-witted idealist, makes a wish so powerful that it is answered by a cosmic force – a little ball of boundless energy called Star. Together, Asha and Star confront a most formidable foe - the ruler of Rosas, King Magnifico - to save her community and prove that when the will of one courageous human connects with the magic of the stars, wondrous things can happen.",
    popularity: 261.635,
    poster_path: "/AcoVfiv1rrWOmAdpnAMnM56ki19.jpg",
    release_date: "2023-11-13",
    title: "Wish",
    video: false,
    vote_average: 6.649,
    vote_count: 111,
  },
  {
    adult: false,
    backdrop_path: "/ptz5ETMxDoRRiE69BVuIxJzyTEO.jpg",
    genre_ids: [16, 35, 12, 10751],
    id: 940551,
    original_language: "en",
    original_title: "Migration",
    overview:
      "After a migrating duck family alights on their pond with thrilling tales of far-flung places, the Mallard family embarks on a family road trip, via New York City, to tropical Jamaica.",
    popularity: 227.663,
    poster_path: "/ldfCF9RhR40mppkzmftxapaHeTo.jpg",
    release_date: "2023-12-06",
    title: "Migration",
    video: false,
    vote_average: 7.6,
    vote_count: 25,
  },
  {
    adult: false,
    backdrop_path: "/pA3vdhadJPxF5GA1uo8OPTiNQDT.jpg",
    genre_ids: [28, 18],
    id: 678512,
    original_language: "en",
    original_title: "Sound of Freedom",
    overview:
      "The story of Tim Ballard, a former US government agent, who quits his job in order to devote his life to rescuing children from global sex traffickers.",
    popularity: 207.359,
    poster_path: "/qA5kPYZA7FkVvqcEfJRoOy4kpHg.jpg",
    release_date: "2023-07-03",
    title: "Sound of Freedom",
    video: false,
    vote_average: 8.085,
    vote_count: 1596,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [99],
    id: 1192578,
    original_language: "es",
    original_title: "Elijo creer",
    overview: "",
    popularity: 180.765,
    poster_path: "/tAX05FIcjnllogMa2r0FmamNhpU.jpg",
    release_date: "2023-12-07",
    title: "Elijo creer",
    video: false,
    vote_average: 8,
    vote_count: 1,
  },
  {
    adult: false,
    backdrop_path: "/ktHEdqmMWC1wdfPRMRCTZe2OISL.jpg",
    genre_ids: [27, 53, 9648],
    id: 1071215,
    original_language: "en",
    original_title: "Thanksgiving",
    overview:
      "After a Black Friday riot ends in tragedy, a mysterious Thanksgiving-inspired killer terrorizes Plymouth, Massachusetts - the birthplace of the holiday. Picking off residents one by one, what begins as random revenge killings are soon revealed to be part of a larger, sinister holiday plan.",
    popularity: 129.823,
    poster_path: "/f5f3TEVst1nHHyqgn7Z3tlwnBIH.jpg",
    release_date: "2023-11-16",
    title: "Thanksgiving",
    video: false,
    vote_average: 6.349,
    vote_count: 106,
  },
  {
    adult: false,
    backdrop_path: "/97MOhHIgU6ZdLcB9DrAhx3WAqrU.jpg",
    genre_ids: [18, 35],
    id: 839369,
    original_language: "en",
    original_title: "May December",
    overview:
      "Twenty years after their notorious tabloid romance gripped the nation, a married couple buckles under pressure when an actress arrives to do research for a film about their past.",
    popularity: 115.756,
    poster_path: "/yibtHDMO70RueiEmtrcJeTiiHFo.jpg",
    release_date: "2023-11-16",
    title: "May December",
    video: false,
    vote_average: 6.72,
    vote_count: 100,
  },
  {
    adult: false,
    backdrop_path: "/3YPP5Buu2lWyRU2YTYRtSqJikWc.jpg",
    genre_ids: [18, 10751, 14],
    id: 1092329,
    original_language: "en",
    original_title: "Journey to Bethlehem",
    overview:
      "A young woman carrying an unimaginable responsibility. A young man torn between love and honor. A jealous king who will stop at nothing to keep his crown.",
    popularity: 107.365,
    poster_path: "/cJgF1vjiNoRAh5UePmiPfjrw6Iv.jpg",
    release_date: "2023-11-09",
    title: "Journey to Bethlehem",
    video: false,
    vote_average: 6.8,
    vote_count: 6,
  },
  {
    adult: false,
    backdrop_path: "/iEFuHjqrE059SmflBva1JzDJutE.jpg",
    genre_ids: [16, 10751, 14, 28, 10749, 10402],
    id: 496450,
    original_language: "fr",
    original_title: "Miraculous - le film",
    overview:
      "A life of an ordinary Parisian teenager Marinette goes superhuman when she becomes Ladybug. Bestowed with magical powers of creation, Ladybug must unite with her opposite, Cat Noir, to save Paris as a new villain unleashes chaos unto the city.",
    popularity: 136.811,
    poster_path: "/dQNJ8SdCMn3zWwHzzQD2xrphR1X.jpg",
    release_date: "2023-07-05",
    title: "Miraculous: Ladybug & Cat Noir, The Movie",
    video: false,
    vote_average: 7.799,
    vote_count: 685,
  },
  {
    adult: false,
    backdrop_path: "/jBOyi3ibJbVa1imTCcddPUxTVAV.jpg",
    genre_ids: [35, 27, 14],
    id: 956920,
    original_language: "no",
    original_title: "There's Something in the Barn",
    overview:
      "An American family fulfills their dream of moving back to their roots after inheriting a remote cabin in the mountains of Norway. But there's a surprise waiting for them.",
    popularity: 115.306,
    poster_path: "/axrzMJR5VPWYNiW9ArENiMEPTjr.jpg",
    release_date: "2023-11-02",
    title: "There's Something in the Barn",
    video: false,
    vote_average: 7.223,
    vote_count: 47,
  },
  {
    adult: false,
    backdrop_path: "/qElNES0sHVQcbzvGrTx7ccpGzij.jpg",
    genre_ids: [878, 28, 18],
    id: 842675,
    original_language: "zh",
    original_title: "流浪地球2",
    overview:
      "Humans built huge engines on the surface of the earth to find a new home. But the road to the universe is perilous. In order to save earth, young people once again have to step forward to start a race against time for life and death.",
    popularity: 124.333,
    poster_path: "/pR858ihc6Ls9xohpdRJVjV787ml.jpg",
    release_date: "2023-01-22",
    title: "The Wandering Earth II",
    video: false,
    vote_average: 7.2,
    vote_count: 409,
  },
  {
    adult: false,
    backdrop_path: "/a0GM57AnJtNi7lMOCamniiyV10W.jpg",
    genre_ids: [16, 12, 14, 18],
    id: 508883,
    original_language: "ja",
    original_title: "君たちはどう生きるか",
    overview:
      "While the Second World War rages, the teenage Mahito, haunted by his mother's tragic death, is relocated from Tokyo to the serene rural home of his new stepmother Natsuko, a woman who bears a striking resemblance to the boy's mother. As he tries to adjust, this strange new world grows even stranger following the appearance of a persistent gray heron, who perplexes and bedevils Mahito, dubbing him the \"long-awaited one.\"",
    popularity: 117.561,
    poster_path: "/jDQPkgzerGophKRRn7MKm071vCU.jpg",
    release_date: "2023-07-14",
    title: "The Boy and the Heron",
    video: false,
    vote_average: 7.2,
    vote_count: 268,
  },
  {
    adult: false,
    backdrop_path: "/gsVC7HMf4VR2XFOyqjTSklY2Tms.jpg",
    genre_ids: [878, 35, 14],
    id: 792307,
    original_language: "en",
    original_title: "Poor Things",
    overview:
      "Brought back to life by an unorthodox scientist, a young woman runs off with a lawyer on a whirlwind adventure across the continents. Free from the prejudices of her times, she grows steadfast in her purpose to stand for equality and liberation.",
    popularity: 105.894,
    poster_path: "/hplhTGTmKoz85Z9UBZ9kYOxtzm0.jpg",
    release_date: "2023-12-07",
    title: "Poor Things",
    video: false,
    vote_average: 8.9,
    vote_count: 7,
  },
  {
    adult: false,
    backdrop_path: "/w1ZeZ8XYTBCovnXi9bwi7D7glM4.jpg",
    genre_ids: [28, 80],
    id: 891699,
    original_language: "en",
    original_title: "Silent Night",
    overview:
      "A tormented father witnesses his young son die when caught in a gang's crossfire on Christmas Eve. While recovering from a wound that costs him his voice, he makes vengeance his life's mission and embarks on a punishing training regimen in order to avenge his son's death.",
    popularity: 83.028,
    poster_path: "/tlcuhdNMKNGEVpGqBZrAaOOf1A6.jpg",
    release_date: "2023-11-30",
    title: "Silent Night",
    video: false,
    vote_average: 6.589,
    vote_count: 45,
  },
  {
    adult: false,
    backdrop_path: "/A1g8AvP3KpDyu0iyjS6roRxK77v.jpg",
    genre_ids: [53, 80],
    id: 978870,
    original_language: "it",
    original_title: "L'ultima notte di Amore",
    overview:
      "On the night before his retirement, police lieutenant Franco Amore is called to investigate the death of a long-time partner of his in a diamond heist in which he was involved.",
    popularity: 91.108,
    poster_path: "/dBp0REsZkZ1HK1PycwlLdBtYdsd.jpg",
    release_date: "2023-03-09",
    title: "Last Night of Amore",
    video: false,
    vote_average: 7.246,
    vote_count: 315,
  },
  {
    adult: false,
    backdrop_path: "/sQLMaESdeELB7Dl8HdxfGlZYRzu.jpg",
    genre_ids: [35, 18],
    id: 840430,
    original_language: "en",
    original_title: "The Holdovers",
    overview:
      "A curmudgeonly instructor at a New England prep school is forced to remain on campus during Christmas break to babysit the handful of students with nowhere to go. Eventually, he forms an unlikely bond with one of them — a damaged, brainy troublemaker — and with the school’s head cook, who has just lost a son in Vietnam.",
    popularity: 84.118,
    poster_path: "/VHSzNBTwxV8vh7wylo7O9CLdac.jpg",
    release_date: "2023-10-27",
    title: "The Holdovers",
    video: false,
    vote_average: 7.707,
    vote_count: 136,
  },
  {
    adult: false,
    backdrop_path: "/pcRCkUtOJ1HSHJ9ZU5mOZ3zpboI.jpg",
    genre_ids: [18, 36],
    id: 906126,
    original_language: "es",
    original_title: "La sociedad de la nieve",
    overview:
      "On October 13, 1972, Uruguayan Air Force Flight 571, chartered to take a rugby team to Chile, crashes into a glacier in the heart of the Andes.",
    popularity: 84.171,
    poster_path: "/k7rEpZfNPB35FFHB00ZhXHKTL7X.jpg",
    release_date: "2023-12-15",
    title: "Society of the Snow",
    video: false,
    vote_average: 7,
    vote_count: 1,
  },
  {
    adult: false,
    backdrop_path: "/rron9HAuS9s7zBF8iCX1tsafxUo.jpg",
    genre_ids: [18, 10749],
    id: 666277,
    original_language: "en",
    original_title: "Past Lives",
    overview:
      "Nora and Hae Sung, two childhood friends, are reunited in New York for one fateful week as they confront notions of destiny, love, and the choices that make a life.",
    popularity: 69.954,
    poster_path: "/k3waqVXSnvCZWfJYNtdamTgTtTA.jpg",
    release_date: "2023-06-02",
    title: "Past Lives",
    video: false,
    vote_average: 7.901,
    vote_count: 359,
  },
  {
    adult: false,
    backdrop_path: "/4kmNLwmVeT3xMciSRefE6SCi2hX.jpg",
    genre_ids: [80, 18, 53],
    id: 1027073,
    original_language: "en",
    original_title: "In the Land of Saints and Sinners",
    overview:
      "In a remote Irish village, a damaged Finbar is forced to fight for redemption after a lifetime of sins, but what price is he willing to pay? In the land of saints and sinners, some sins can't be buried.",
    popularity: 71.866,
    poster_path: "/jN8JJaVpADPEU6SZX8QBCZHAFrU.jpg",
    release_date: "2023-10-06",
    title: "In the Land of Saints and Sinners",
    video: false,
    vote_average: 6.563,
    vote_count: 48,
  },
  {
    adult: false,
    backdrop_path: "/hsdwzxdX7oHWa7SX4dMAMuq2RqJ.jpg",
    genre_ids: [18, 36],
    id: 365620,
    original_language: "en",
    original_title: "Ferrari",
    overview:
      "A biopic of automotive mogul Enzo Ferrari, whose family redefined the idea of the high-powered Italian sports car and practically spawned the concept of Formula One racing.",
    popularity: 63.357,
    poster_path: "/dAP9QTLVvglGvtsa0VesaOgHcTW.jpg",
    release_date: "2023-12-14",
    title: "Ferrari",
    video: false,
    vote_average: 7.1,
    vote_count: 19,
  },
  {
    adult: false,
    backdrop_path: "/lr2kcIbCgP7Q06DV5Hfs3J6yuJy.jpg",
    genre_ids: [12, 28],
    id: 845111,
    original_language: "fr",
    original_title: "Les trois mousquetaires : Milady",
    overview:
      "The second of a two-part film adaptation of Alexandre Dumas' novel. Constance is kidnapped before D'Artagnan's eyes. In a frantic quest to save her, the young musketeer is forced to join forces with the mysterious Milady de Winter. But as war is declared and Athos, Porthos and Aramis have already joined the front, a terrible secret from the past shatters all old alliances. As the King falls further and further under the control of Cardinal Richelieu, D'Artagnan and the Musketeers are the last bastions before chaos. But, drawn into a plot that threatens to put the country to fire and sword, fate presents them with a terrible choice: will they have to sacrifice those they love to complete their mission?",
    popularity: 58.594,
    poster_path: "/2g3BSuUFsa88SgeMP7tlv9x92Mz.jpg",
    release_date: "2023-12-13",
    title: "The Three Musketeers: Milady",
    video: false,
    vote_average: 6.886,
    vote_count: 22,
  },
  {
    adult: false,
    backdrop_path: "/1PkBhxXdEejw8c5BC7T3cN7jz9g.jpg",
    genre_ids: [35, 10749],
    id: 1072790,
    original_language: "en",
    original_title: "Anyone But You",
    overview:
      "After an amazing first date, Bea and Ben's fiery attraction turns ice cold - until they find themselves unexpectedly reunited at a destination wedding in Australia. So they do what any two mature adults would do: pretend to be a couple.",
    popularity: 56.31,
    poster_path: "/xvPCsU1iwAQJpJZOuHyYtFpwV1R.jpg",
    release_date: "2023-12-21",
    title: "Anyone But You",
    video: false,
    vote_average: 10,
    vote_count: 1,
  },
  {
    adult: false,
    backdrop_path: "/H8YE8DDrnvr869RgCqLvhfcUFM.jpg",
    genre_ids: [18],
    id: 970348,
    original_language: "en",
    original_title: "The Old Oak",
    overview:
      "A pub landlord in a previously thriving mining community struggles to hold onto his pub. Meanwhile, tensions rise in the town when Syrian refugees are placed in the empty houses in the community.",
    popularity: 35.405,
    poster_path: "/xN293BKB0MDqpILmLCtGGYxQXKW.jpg",
    release_date: "2023-09-29",
    title: "The Old Oak",
    video: false,
    vote_average: 7.4,
    vote_count: 120,
  },
  {
    adult: false,
    backdrop_path: "/cru4rjGcdHGhnPyjNXvW82jOrif.jpg",
    genre_ids: [35, 18, 10749],
    id: 986280,
    original_language: "fi",
    original_title: "Kuolleet lehdet",
    overview:
      "The film tells the story of Ansa, a supermarket shelf-stocker on a zero-hour contract, later a recyclable plastic sorter, and Holappa, a sandblaster, an alcoholic, later an ex-alcoholic, whose paths have accidentally crossed and who, despite adversity and misunderstandings, try to build some kind of relationship on the harsher side of state welfare.",
    popularity: 34.41,
    poster_path: "/ca9341N5crOnOCPhCJhQu0iYcTb.jpg",
    release_date: "2023-09-14",
    title: "Fallen Leaves",
    video: false,
    vote_average: 7,
    vote_count: 86,
  },
  {
    adult: false,
    backdrop_path: "/1aRQfzerE6M0vnXMdR2BFUlAoOx.jpg",
    genre_ids: [16, 35, 10751, 14],
    id: 923579,
    original_language: "ru",
    original_title: "Коты Эрмитажа",
    overview:
      "A cartoon about the famous four-legged inhabitants of the St. Petersburg Winter Palace - museum cats that protect the territory of the State Hermitage from rats and mice.",
    popularity: 40.704,
    poster_path: "/3NrXKidbEsViHq3aLvmX1FEncna.jpg",
    release_date: "2023-03-23",
    title: "Cats in the Museum",
    video: false,
    vote_average: 7.2,
    vote_count: 36,
  },
  {
    adult: false,
    backdrop_path: "/bx6ipM7K7hF6B974POq5PkbqfNc.jpg",
    genre_ids: [14, 35],
    id: 823482,
    original_language: "en",
    original_title: "Dream Scenario",
    overview:
      "Hapless family man Paul Matthews finds his life turned upside down when millions of strangers suddenly start seeing him in their dreams. But when his nighttime appearances take a nightmarish turn, Paul is forced to navigate his newfound stardom.",
    popularity: 42.071,
    poster_path: "/eMaAi8wTI5wON8pp33w3BDuGyZ8.jpg",
    release_date: "2023-11-10",
    title: "Dream Scenario",
    video: false,
    vote_average: 7.5,
    vote_count: 57,
  },
  {
    adult: false,
    backdrop_path: "/d1xgTgcAd5VKDbXwLfnlM9OIWfP.jpg",
    genre_ids: [12, 27, 28, 36],
    id: 6312,
    original_language: "fr",
    original_title: "Le Pacte des loups",
    overview:
      "In 18th century France, the Chevalier de Fronsac and his Native American friend Mani are sent by the King to the Gevaudan province to investigate the killings of hundreds by a mysterious beast.",
    popularity: 29.53,
    poster_path: "/x0bsgEeWqpvH8Lgwgmzi2tujlrV.jpg",
    release_date: "2001-01-31",
    title: "Brotherhood of the Wolf",
    video: false,
    vote_average: 6.7,
    vote_count: 1385,
  },
  {
    adult: false,
    backdrop_path: "/c7MRmF3LMiBWokedmdQl3roTUv2.jpg",
    genre_ids: [53, 18],
    id: 798362,
    original_language: "en",
    original_title: "The Marsh King's Daughter",
    overview:
      "Helena, a woman living a seemingly ordinary life, hides a dark secret—her father is the infamous 'Marsh King', the man who kept her and her mother captive in the wilderness for years. After a lifetime of trying to escape her past, Helena is forced to face her demons when her father unexpectedly escapes from prison.",
    popularity: 53.437,
    poster_path: "/bcuEjrwhp5HgEUnFe5lc4xpEqzt.jpg",
    release_date: "2023-09-28",
    title: "The Marsh King's Daughter",
    video: false,
    vote_average: 6.8,
    vote_count: 51,
  },
  {
    adult: false,
    backdrop_path: "/3xYPGRUsXCZj7rKOzvOY84JCafK.jpg",
    genre_ids: [36, 18, 10749],
    id: 1020006,
    original_language: "en",
    original_title: "Priscilla",
    overview:
      "When teenage Priscilla Beaulieu meets Elvis Presley at a party, the man who is already a meteoric rock-and-roll superstar becomes someone entirely unexpected in private moments: a thrilling crush, an ally in loneliness, a vulnerable best friend.",
    popularity: 47.449,
    poster_path: "/2JCATDCP1UQ2TbJ1jNTTf43F2p5.jpg",
    release_date: "2023-10-27",
    title: "Priscilla",
    video: false,
    vote_average: 7.141,
    vote_count: 46,
  },
  {
    adult: false,
    backdrop_path: "/9DYLQLBbLr5943lNS2gihQZpfc8.jpg",
    genre_ids: [28, 18, 80],
    id: 944401,
    original_language: "fr",
    original_title: "Dogman",
    overview:
      "A boy, bruised by life, finds his salvation through the love of his dogs.",
    popularity: 38.47,
    poster_path: "/xExDMuJHS0tqEfXGWUOR5rjP6xK.jpg",
    release_date: "2023-09-27",
    title: "Dogman",
    video: false,
    vote_average: 7.426,
    vote_count: 169,
  },
  {
    adult: false,
    backdrop_path: "/uJwTRJxMnZcnDTyesNyeZhkHaOp.jpg",
    genre_ids: [35, 18],
    id: 621587,
    original_language: "en",
    original_title: "Next Goal Wins",
    overview:
      "Dutch coach Thomas Rongen attempts the nearly impossible task of turning the American Samoa soccer team from perennial losers into winners.",
    popularity: 47.177,
    poster_path: "/zWmKqcox4AgM3deEEVCeYqEOOJ2.jpg",
    release_date: "2023-11-16",
    title: "Next Goal Wins",
    video: false,
    vote_average: 6.281,
    vote_count: 16,
  },
  {
    adult: false,
    backdrop_path: "/jqFjgNnxpXIXWuPsyfqmcLXRo9p.jpg",
    genre_ids: [80, 53],
    id: 500,
    original_language: "en",
    original_title: "Reservoir Dogs",
    overview:
      "A botched robbery indicates a police informant, and the pressure mounts in the aftermath at a warehouse. Crime begets violence as the survivors -- veteran Mr. White, newcomer Mr. Orange, psychopathic parolee Mr. Blonde, bickering weasel Mr. Pink and Nice Guy Eddie -- unravel.",
    popularity: 52.356,
    poster_path: "/xi8Iu6qyTfyZVDVy60raIOYJJmk.jpg",
    release_date: "1992-09-02",
    title: "Reservoir Dogs",
    video: false,
    vote_average: 8.131,
    vote_count: 13471,
  },
  {
    adult: false,
    backdrop_path: "/nlPCdZlHtRNcF6C9hzUH4ebmV1w.jpg",
    genre_ids: [35, 18, 10749, 10402],
    id: 313369,
    original_language: "en",
    original_title: "La La Land",
    overview:
      "Mia, an aspiring actress, serves lattes to movie stars in between auditions and Sebastian, a jazz musician, scrapes by playing cocktail party gigs in dingy bars, but as success mounts they are faced with decisions that begin to fray the fragile fabric of their love affair, and the dreams they worked so hard to maintain in each other threaten to rip them apart.",
    popularity: 55.759,
    poster_path: "/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
    release_date: "2016-11-29",
    title: "La La Land",
    video: false,
    vote_average: 7.901,
    vote_count: 15779,
  },
  {
    adult: false,
    backdrop_path: "/i3FuO7aSoVRoS63if3aetJYJJjF.jpg",
    genre_ids: [27, 53],
    id: 977013,
    original_language: "en",
    original_title: "Haunting of the Queen Mary",
    overview:
      "When photographers Erin and Patrick are brought aboard the ship with their young son Lukas, they unleash a series of events that entwines their family with the ship’s dark past. As the terror unfolds around them they begin to realise there is more to this sumptuous ocean liner than meets the eye: its remarkable legacy masking violent secrets.",
    popularity: 44.144,
    poster_path: "/1uNMAlNanIQohAofjyyad2WVCdk.jpg",
    release_date: "2023-07-19",
    title: "Haunting of the Queen Mary",
    video: false,
    vote_average: 4.705,
    vote_count: 44,
  },
  {
    adult: false,
    backdrop_path: "/bP9h1qHuFQIDERuGXt43Q3TfBdg.jpg",
    genre_ids: [27],
    id: 1146143,
    original_language: "en",
    original_title: "The Puppetman",
    overview:
      "The Puppetman, a convicted killer on death row always maintained his innocence saying that it was an evil force controlling his body as he slaughtered his victims. Now Michal, the killer's daughter, begins to suspect that there may be some truth to her father's claim when those around her begin to die in brutal ways. She must try and break the curse of The Puppetman before all her loved ones are killed.",
    popularity: 37.948,
    poster_path: "/wEnct8jeMHYzOfm5Y6QmxD3V61t.jpg",
    release_date: "2023-12-22",
    title: "The Puppetman",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
];

var suggestion = [
  {
    adult: false,
    backdrop_path: "/1X7vow16X7CnCoexXh4H4F2yDJv.jpg",
    genre_ids: [80, 18, 36],
    id: 466420,
    original_language: "en",
    original_title: "Killers of the Flower Moon",
    overview:
      "When oil is discovered in 1920s Oklahoma under Osage Nation land, the Osage people are murdered one by one—until the FBI steps in to unravel the mystery.",
    popularity: 1414.987,
    poster_path: "/dB6Krk806zeqd0YNp2ngQ9zXteH.jpg",
    release_date: "2023-10-18",
    title: "Killers of the Flower Moon",
    video: false,
    vote_average: 7.64,
    vote_count: 1400,
  },
  {
    adult: false,
    backdrop_path: "/zIYROrkHJPYB3VTiW1L9QVgaQO.jpg",
    genre_ids: [28, 35],
    id: 897087,
    original_language: "en",
    original_title: "Freelance",
    overview:
      "An ex-special forces operative takes a job to provide security for a journalist as she interviews a dictator, but a military coup breaks out in the middle of the interview, they are forced to escape into the jungle where they must survive.",
    popularity: 1229.045,
    poster_path: "/7Bd4EUOqQDKZXA6Od5gkfzRNb0.jpg",
    release_date: "2023-01-05",
    title: "Freelance",
    video: false,
    vote_average: 6.436,
    vote_count: 295,
  },
  {
    adult: false,
    backdrop_path: "/jVFeUR259RcW57mzhqJogV3QnLa.jpg",
    genre_ids: [28, 53, 18],
    id: 656156,
    original_language: "ko",
    original_title: "보호자",
    overview:
      "After 10 years of incarceration on behalf of his employer, all Su-hyuk wants is a normal life - one he hopes will include his former girlfriend, Min-seo, and their daughter, In-bi. But once you've penetrated the upper echelons of the underworld, normal can prove hard to come by. Sometime in the past decade, meanwhile, Su-hyuk's employer has adopted an air of legitimacy. These days, the old gang steal and murder in the name of urban development. And they want the reluctant Su-hyuk on board.",
    popularity: 969.491,
    poster_path: "/ePwZs1oOh4pg8UZP8DuVZZeIn89.jpg",
    release_date: "2023-08-15",
    title: "A Man of Reason",
    video: false,
    vote_average: 6.46,
    vote_count: 25,
  },
  {
    adult: false,
    backdrop_path: "/tLsc8SCFO0rMVgVyNm9XtfnyX84.jpg",
    genre_ids: [18, 9648, 53, 878],
    id: 726209,
    original_language: "en",
    original_title: "Leave the World Behind",
    overview:
      "A family's getaway to a luxurious rental home takes an ominous turn when a cyberattack knocks out their devices—and two strangers appear at their door.",
    popularity: 989.94,
    poster_path: "/5qhtTPWNqzM1eo9QIIf5cyIUeAA.jpg",
    release_date: "2023-11-22",
    title: "Leave the World Behind",
    video: false,
    vote_average: 6.667,
    vote_count: 692,
  },
  {
    adult: false,
    backdrop_path: "/yOm993lsJyPmBodlYjgpPwBjXP9.jpg",
    genre_ids: [35, 10751, 14],
    id: 787699,
    original_language: "en",
    original_title: "Wonka",
    overview:
      "Willy Wonka – chock-full of ideas and determined to change the world one delectable bite at a time – is proof that the best things in life begin with a dream, and if you’re lucky enough to meet Willy Wonka, anything is possible.",
    popularity: 974.471,
    poster_path: "/qhb1qOilapbapxWQn9jtRCMwXJF.jpg",
    release_date: "2023-12-06",
    title: "Wonka",
    video: false,
    vote_average: 7.256,
    vote_count: 195,
  },
  {
    adult: false,
    backdrop_path: "/k1KrbaCMACQiq7EA0Yhw3bdzMv7.jpg",
    genre_ids: [16, 10751, 10402, 14, 35],
    id: 901362,
    original_language: "en",
    original_title: "Trolls Band Together",
    overview:
      "When Branch's brother, Floyd, is kidnapped for his musical talents by a pair of nefarious pop-star villains, Branch and Poppy embark on a harrowing and emotional journey to reunite the other brothers and rescue Floyd from a fate even worse than pop-culture obscurity.",
    popularity: 901.938,
    poster_path: "/sEaLO9s7CIN3fjz8R3Qksum44en.jpg",
    release_date: "2023-10-12",
    title: "Trolls Band Together",
    video: false,
    vote_average: 7.168,
    vote_count: 361,
  },
  {
    adult: false,
    backdrop_path: "/9PqD3wSIjntyJDBzMNuxuKHwpUD.jpg",
    genre_ids: [16, 35, 10751],
    id: 1075794,
    original_language: "en",
    original_title: "Leo",
    overview:
      "Jaded 74-year-old lizard Leo has been stuck in the same Florida classroom for decades with his terrarium-mate turtle. When he learns he only has one year left to live, he plans to escape to experience life on the outside but instead gets caught up in the problems of his anxious students — including an impossibly mean substitute teacher.",
    popularity: 809.49,
    poster_path: "/pD6sL4vntUOXHmuvJPPZAgvyfd9.jpg",
    release_date: "2023-11-17",
    title: "Leo",
    video: false,
    vote_average: 7.625,
    vote_count: 561,
  },
  {
    adult: false,
    backdrop_path: "/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg",
    genre_ids: [18, 36],
    id: 872585,
    original_language: "en",
    original_title: "Oppenheimer",
    overview:
      "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.",
    popularity: 661.264,
    poster_path: "/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    release_date: "2023-07-19",
    title: "Oppenheimer",
    video: false,
    vote_average: 8.132,
    vote_count: 5408,
  },
  {
    adult: false,
    backdrop_path: "/AucuqDaUW4z1oT5XyL71qwRY2F6.jpg",
    genre_ids: [27, 53],
    id: 983507,
    original_language: "no",
    original_title: "Meg, deg & Frank",
    overview:
      "Christian - a millionaire heir, meets Sigrid - a young student, on a dating app. They hit it off quickly, but there's only one problem: Christian lives with Frank, a man who dresses up and constantly acts like a dog.",
    popularity: 842.589,
    poster_path: "/9DPG1gxLwV2oyFdHq3SnISsWbse.jpg",
    release_date: "2022-06-03",
    title: "Good Boy",
    video: false,
    vote_average: 6.856,
    vote_count: 101,
  },
  {
    adult: false,
    backdrop_path: "/jhpsTzbXEu5bkCPmBqxv7vUTjIT.jpg",
    genre_ids: [14, 12, 878, 28],
    id: 566810,
    original_language: "en",
    original_title: "Dragon Kingdom",
    overview:
      "To save their Kingdom from an army of undead, a group of warriors must travel through the forbidden lands fighting the fearsome beasts that call The Dark Kingdom their home.",
    popularity: 614.418,
    poster_path: "/o7StI2iR8yY1N67meSkNcXfojyD.jpg",
    release_date: "2018-11-26",
    title: "The Dark Kingdom",
    video: false,
    vote_average: 5.7,
    vote_count: 41,
  },
  {
    adult: false,
    backdrop_path: "/lDlVgD9IGAmki7CgIlH5eYUwrhW.jpg",
    genre_ids: [28, 12, 878],
    id: 857879,
    original_language: "en",
    original_title: "Mount Adams",
    overview:
      "UFO investigators find themselves fighting for survival as alien monsters hunt them on the slopes of Mount Adams.",
    popularity: 583.477,
    poster_path: "/nddTKKAu6z771duaxr1D32pHZ8j.jpg",
    release_date: "2021-07-21",
    title: "Mount Adams",
    video: false,
    vote_average: 6.5,
    vote_count: 8,
  },
  {
    adult: false,
    backdrop_path: "/mIpdOcss3oedSYB8juiSXg89uLL.jpg",
    genre_ids: [28, 878, 12, 53],
    id: 479753,
    original_language: "en",
    original_title: "Shockwave: Countdown to Disaster",
    overview:
      "A stolen seismic weapon is activated in Yemen. A hostage freed there tries in vain to warn against its global effect. It starts seismic activity at the Californian fault line where her daughter and ex are monitoring it. Can they stop it?",
    popularity: 539.137,
    poster_path: "/sBD608VF4TcFHmP7SuC0OcvZQ0b.jpg",
    release_date: "2017-09-02",
    title: "Shockwave: Countdown to Disaster",
    video: false,
    vote_average: 5.652,
    vote_count: 56,
  },
  {
    adult: false,
    backdrop_path: "/rb3QQ2TQfJoCpCZlfXBlBbzYy1D.jpg",
    genre_ids: [53, 28],
    id: 844416,
    original_language: "en",
    original_title: "Rumble Through the Dark",
    overview:
      "Set in the dark landscape of the Mississippi Delta, where a former bare-knuckle fighter must win one last fight to pay off his debts to the local mob boss and save his childhood home—the stakes nothing less than life or death.",
    popularity: 737.013,
    poster_path: "/19UbYIT9WEQS5qSD3BREDxVXk8g.jpg",
    release_date: "2023-11-03",
    title: "Rumble Through the Dark",
    video: false,
    vote_average: 6.659,
    vote_count: 22,
  },
  {
    adult: false,
    backdrop_path: "/uOvcyJ3XmUv4geypGvZBeZEFMO6.jpg",
    genre_ids: [28, 80, 18],
    id: 945937,
    original_language: "en",
    original_title: "Fast Charlie",
    overview:
      "When his aging mob boss is whacked, Charlie Swift, a loyal friend and hired gun, will stop at nothing to destroy the upcoming crew that took him out.",
    popularity: 651.192,
    poster_path: "/3y72ffwYRUPOj4yOQbiTaN897Tm.jpg",
    release_date: "2023-12-08",
    title: "Fast Charlie",
    video: false,
    vote_average: 6.143,
    vote_count: 21,
  },
  {
    adult: false,
    backdrop_path: "/t5zCBSB5xMDKcDqe91qahCOUYVV.jpg",
    genre_ids: [27, 9648],
    id: 507089,
    original_language: "en",
    original_title: "Five Nights at Freddy's",
    overview:
      "Recently fired and desperate for work, a troubled young man named Mike agrees to take a position as a night security guard at an abandoned theme restaurant: Freddy Fazbear's Pizzeria. But he soon discovers that nothing at Freddy's is what it seems.",
    popularity: 608.419,
    poster_path: "/7BpNtNfxuocYEVREzVMO75hso1l.jpg",
    release_date: "2023-10-25",
    title: "Five Nights at Freddy's",
    video: false,
    vote_average: 7.829,
    vote_count: 2835,
  },
  {
    adult: false,
    backdrop_path: "/3xvdNyZ9WsVJpyeGhm85fukeZz4.jpg",
    genre_ids: [878, 9648, 53],
    id: 1001835,
    original_language: "en",
    original_title: "Wifelike",
    overview:
      "A grieving detective in the near-future hunts down criminals who trade artificial humans on the black market. In the fight to end AI exploitation, an underground resistance attempts to infiltrate him by sabotaging the programming of the artificial human assigned as his companion to behave like his late wife. She begins to question her reality as memories of a past life begin to surface in a world where nothing is as it seems.",
    popularity: 504.583,
    poster_path: "/tea2gDZPxw0wfKC2S2VRWHagtt4.jpg",
    release_date: "2022-08-12",
    title: "Wifelike",
    video: false,
    vote_average: 7.033,
    vote_count: 200,
  },
  {
    adult: false,
    backdrop_path: "/4XM8DUTQb3lhLemJC51Jx4a2EuA.jpg",
    genre_ids: [28, 80, 53],
    id: 385687,
    original_language: "en",
    original_title: "Fast X",
    overview:
      "Over many missions and against impossible odds, Dom Toretto and his family have outsmarted, out-nerved and outdriven every foe in their path. Now, they confront the most lethal opponent they've ever faced: A terrifying threat emerging from the shadows of the past who's fueled by blood revenge, and who is determined to shatter this family and destroy everything—and everyone—that Dom loves, forever.",
    popularity: 555.079,
    poster_path: "/fiVW06jE7z9YnO4trhaMEdclSiC.jpg",
    release_date: "2023-05-17",
    title: "Fast X",
    video: false,
    vote_average: 7.198,
    vote_count: 4462,
  },
  {
    adult: false,
    backdrop_path: "/evxXVJtomJJbAXcDxF6wsCJzVDe.jpg",
    genre_ids: [27],
    id: 1019836,
    original_language: "en",
    original_title: "Christmas Bloody Christmas",
    overview:
      "It's Christmas Eve and Tori just wants to get drunk and party, but when a robotic Santa Claus at a nearby toy store goes haywire and begins a rampant killing spree through her small town, she's forced into a battle for survival.",
    popularity: 524.144,
    poster_path: "/97PaQ7r4H3y0x9RTXusfedmzf86.jpg",
    release_date: "2022-10-05",
    title: "Christmas Bloody Christmas",
    video: false,
    vote_average: 5.6,
    vote_count: 148,
  },
  {
    adult: false,
    backdrop_path: "/h3X1YZXNeklLNKRVOS6DHGRosog.jpg",
    genre_ids: [27, 35, 14],
    id: 287903,
    original_language: "en",
    original_title: "Krampus",
    overview:
      "When his dysfunctional family clashes over the holidays, young Max is disillusioned and turns his back on Christmas.  Little does he know, this lack of festive spirit has unleashed the wrath of Krampus: a demonic force of ancient evil intent on punishing non-believers.",
    popularity: 530.061,
    poster_path: "/sAolMRD9rFSTU7tssfFuLEJJa7w.jpg",
    release_date: "2015-11-26",
    title: "Krampus",
    video: false,
    vote_average: 6.2,
    vote_count: 1971,
  },
];
var toprating = [
  {
    adult: false,
    backdrop_path: "/tmU7GeKVybMWFButWEGl2M4GeiP.jpg",
    genre_ids: [18, 80],
    id: 238,
    original_language: "en",
    original_title: "The Godfather",
    overview:
      "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.",
    popularity: 146.667,
    poster_path: "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    release_date: "1972-03-14",
    title: "The Godfather",
    video: false,
    vote_average: 8.708,
    vote_count: 19115,
  },
  {
    adult: false,
    backdrop_path: "/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg",
    genre_ids: [18, 80],
    id: 278,
    original_language: "en",
    original_title: "The Shawshank Redemption",
    overview:
      "Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.",
    popularity: 110.352,
    poster_path: "/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
    release_date: "1994-09-23",
    title: "The Shawshank Redemption",
    video: false,
    vote_average: 8.706,
    vote_count: 25108,
  },
  {
    adult: false,
    backdrop_path: "/kGzFbGhp99zva6oZODW5atUtnqi.jpg",
    genre_ids: [18, 80],
    id: 240,
    original_language: "en",
    original_title: "The Godfather Part II",
    overview:
      "In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.",
    popularity: 98.103,
    poster_path: "/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg",
    release_date: "1974-12-20",
    title: "The Godfather Part II",
    video: false,
    vote_average: 8.588,
    vote_count: 11532,
  },
  {
    adult: false,
    backdrop_path: "/3f92DMBTFqr3wgXpfxzrb0qv8nG.jpg",
    genre_ids: [18, 36, 10752],
    id: 424,
    original_language: "en",
    original_title: "Schindler's List",
    overview:
      "The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.",
    popularity: 96.183,
    poster_path: "/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
    release_date: "1993-12-15",
    title: "Schindler's List",
    video: false,
    vote_average: 8.573,
    vote_count: 14880,
  },
  {
    adult: false,
    backdrop_path: "/90ez6ArvpO8bvpyIngBuwXOqJm5.jpg",
    genre_ids: [35, 18, 10749],
    id: 19404,
    original_language: "hi",
    original_title: "दिलवाले दुल्हनिया ले जायेंगे",
    overview:
      "Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.",
    popularity: 32.441,
    poster_path: "/lfRkUr7DYdHldAqi3PwdQGBRBPM.jpg",
    release_date: "1995-10-20",
    title: "Dilwale Dulhania Le Jayenge",
    video: false,
    vote_average: 8.547,
    vote_count: 4301,
  },
  {
    adult: false,
    backdrop_path: "/qqHQsStV6exghCM7zbObuYBiYxw.jpg",
    genre_ids: [18],
    id: 389,
    original_language: "en",
    original_title: "12 Angry Men",
    overview:
      "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
    popularity: 58.439,
    poster_path: "/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg",
    release_date: "1957-04-10",
    title: "12 Angry Men",
    video: false,
    vote_average: 8.544,
    vote_count: 7855,
  },
  {
    adult: false,
    backdrop_path: "/mSDsSDwaP3E7dEfUPWy4J0djt4O.jpg",
    genre_ids: [16, 10751, 14],
    id: 129,
    original_language: "ja",
    original_title: "千と千尋の神隠し",
    overview:
      "A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.",
    popularity: 93.241,
    poster_path: "/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
    release_date: "2001-07-20",
    title: "Spirited Away",
    video: false,
    vote_average: 8.539,
    vote_count: 15214,
  },
  {
    adult: false,
    backdrop_path: "/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg",
    genre_ids: [35, 53, 18],
    id: 496243,
    original_language: "ko",
    original_title: "기생충",
    overview:
      "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
    popularity: 70.796,
    poster_path: "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    release_date: "2019-05-30",
    title: "Parasite",
    video: false,
    vote_average: 8.513,
    vote_count: 16773,
  },
  {
    adult: false,
    backdrop_path: "/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg",
    genre_ids: [18, 28, 80, 53],
    id: 155,
    original_language: "en",
    original_title: "The Dark Knight",
    overview:
      "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
    popularity: 119.46,
    poster_path: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    release_date: "2008-07-16",
    title: "The Dark Knight",
    video: false,
    vote_average: 8.512,
    vote_count: 31056,
  },
  {
    adult: false,
    backdrop_path: "/l6hQWH9eDksNJNiXWYRkWqikOdu.jpg",
    genre_ids: [14, 18, 80],
    id: 497,
    original_language: "en",
    original_title: "The Green Mile",
    overview:
      "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
    popularity: 75.043,
    poster_path: "/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg",
    release_date: "1999-12-10",
    title: "The Green Mile",
    video: false,
    vote_average: 8.509,
    vote_count: 16225,
  },
  {
    adult: false,
    backdrop_path: "/dIWwZW7dJJtqC6CgWzYkNVKIUm8.jpg",
    genre_ids: [10749, 16, 18],
    id: 372058,
    original_language: "ja",
    original_title: "君の名は。",
    overview:
      "High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.",
    popularity: 80.255,
    poster_path: "/q719jXXEzOoYaps6babgKnONONX.jpg",
    release_date: "2016-08-26",
    title: "Your Name.",
    video: false,
    vote_average: 8.5,
    vote_count: 10575,
  },
  {
    adult: false,
    backdrop_path: "/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
    genre_ids: [53, 80],
    id: 680,
    original_language: "en",
    original_title: "Pulp Fiction",
    overview:
      "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
    popularity: 104.789,
    poster_path: "/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    release_date: "1994-09-10",
    title: "Pulp Fiction",
    video: false,
    vote_average: 8.489,
    vote_count: 26269,
  },
  {
    adult: false,
    backdrop_path: "/9DeGfFIqjph5CBFVQrD6wv9S7rR.jpg",
    genre_ids: [12, 14, 28],
    id: 122,
    original_language: "en",
    original_title: "The Lord of the Rings: The Return of the King",
    overview:
      "Aragorn is revealed as the heir to the ancient kings as he, Gandalf and the other members of the broken fellowship struggle to save Gondor from Sauron's forces. Meanwhile, Frodo and Sam take the ring closer to the heart of Mordor, the dark lord's realm.",
    popularity: 90.857,
    poster_path: "/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
    release_date: "2003-12-01",
    title: "The Lord of the Rings: The Return of the King",
    video: false,
    vote_average: 8.476,
    vote_count: 22699,
  },
  {
    adult: false,
    backdrop_path: "/qdIMHd4sEfJSckfVJfKQvisL02a.jpg",
    genre_ids: [35, 18, 10749],
    id: 13,
    original_language: "en",
    original_title: "Forrest Gump",
    overview:
      "A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.",
    popularity: 88.451,
    poster_path: "/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
    release_date: "1994-06-23",
    title: "Forrest Gump",
    video: false,
    vote_average: 8.476,
    vote_count: 25791,
  },
  {
    adult: false,
    backdrop_path: "/eoCSp75lxatmIa6aGqfnzwtbttd.jpg",
    genre_ids: [37],
    id: 429,
    original_language: "it",
    original_title: "Il buono, il brutto, il cattivo",
    overview:
      "While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.",
    popularity: 66.265,
    poster_path: "/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg",
    release_date: "1966-12-23",
    title: "The Good, the Bad and the Ugly",
    video: false,
    vote_average: 8.471,
    vote_count: 7931,
  },
  {
    adult: false,
    backdrop_path: "/sw7mordbZxgITU877yTpZCud90M.jpg",
    genre_ids: [18, 80],
    id: 769,
    original_language: "en",
    original_title: "GoodFellas",
    overview:
      "The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.",
    popularity: 70.627,
    poster_path: "/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg",
    release_date: "1990-09-12",
    title: "GoodFellas",
    video: false,
    vote_average: 8.5,
    vote_count: 11964,
  },
  {
    adult: false,
    backdrop_path: "/dlC0ed9Ugh3FzydnkBtV5lRXUu4.jpg",
    genre_ids: [16, 18, 10752],
    id: 12477,
    original_language: "ja",
    original_title: "火垂るの墓",
    overview:
      "In the final months of World War II, 14-year-old Seita and his sister Setsuko are orphaned when their mother is killed during an air raid in Kobe, Japan. After a falling out with their aunt, they move into an abandoned bomb shelter. With no surviving relatives and their emergency rations depleted, Seita and Setsuko struggle to survive.",
    popularity: 0.6,
    poster_path: "/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg",
    release_date: "1988-04-15",
    title: "Grave of the Fireflies",
    video: false,
    vote_average: 8.455,
    vote_count: 4980,
  },
  {
    adult: false,
    backdrop_path: "/gavyCu1UaTaTNPsVaGXT6pe5u24.jpg",
    genre_ids: [35, 18],
    id: 637,
    original_language: "it",
    original_title: "La vita è bella",
    overview:
      "A touching story of an Italian book seller of Jewish ancestry who lives in his own little fairy tale. His creative and happy life would come to an abrupt halt when his entire family is deported to a concentration camp during World War II. While locked up he tries to convince his son that the whole thing is just a game.",
    popularity: 42.424,
    poster_path: "/6tEJnof1DKWPnl5lzkjf0FVv7oB.jpg",
    release_date: "1997-12-20",
    title: "Life Is Beautiful",
    video: false,
    vote_average: 8.455,
    vote_count: 12402,
  },
  {
    adult: false,
    backdrop_path: "/qvZ91FwMq6O47VViAr8vZNQz3WI.jpg",
    genre_ids: [28, 18],
    id: 346,
    original_language: "ja",
    original_title: "七人の侍",
    overview:
      "A samurai answers a village's request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves, and the villagers provide the soldiers with food.",
    popularity: 44.973,
    poster_path: "/8OKmBV5BUFzmozIC3pPWKHy17kx.jpg",
    release_date: "1954-04-26",
    title: "Seven Samurai",
    video: false,
    vote_average: 8.455,
    vote_count: 3318,
  },
  {
    adult: false,
    backdrop_path: "/zoVeIgKzGJzpdG6Gwnr7iOYfIMU.jpg",
    genre_ids: [18, 10749],
    id: 11216,
    original_language: "it",
    original_title: "Nuovo Cinema Paradiso",
    overview:
      "A filmmaker recalls his childhood, when he fell in love with the movies at his village's theater and formed a deep friendship with the theater's projectionist.",
    popularity: 37.349,
    poster_path: "/8SRUfRUi6x4O68n0VCbDNRa6iGL.jpg",
    release_date: "1988-11-17",
    title: "Cinema Paradiso",
    video: false,
    vote_average: 8.448,
    vote_count: 4038,
  },
];
let movies = [
  {
    id: 2734,
    packdrop_path:
      "https://image.tmdb.org/t/p/original/9xxLWtnFxkpJ2h1uthpvCRK6vta.jpg",
    first_aired: "1999-09-20",
    genres: ["Crie", "Drama", "Mystery"],
    original_title: "Law & Order: Special Victims Unit",
    overview:
      "In the criminal justice system, sexually-based offenses are considered especially heinous. In New York City, the dedicated detectives who investigate these vicious felonies are members of an elite squad known as the Special Victims Unit. These are their stories.",
    poster_path:
      "https://image.tmdb.org/t/p/original/ywBt4WKADdMVgxTR1rS2uFwMYTH.jpg",
    title: "Law & Order: Special Victims Unit",
  },
  {
    id: 456,
    packdrop_path:
      "https://image.tmdb.org/t/p/original/uNyEVSPeAtJgUBehuQJ8WEFwatN.jpg",
    first_aired: "189-12-17",
    genres: ["Famiy", "Animation", "Comedy"],
    original_title: "The Simpsons",
    overview:
      "Set in Springfield, the average American town, the show focuses on the antics and everyday adventures of the Simpson family; Homer, Marge, Bart, Lisa and Maggie, as well as a virtual cast of thousands. Since the beginning, the series has been a pop culture icon, attracting hundreds of celebrities to guest star. The show has also made name for itself in its fearless satirical take on politics, media and American life in general.",
    poster_path:
      "https://image.tmdb.org/t/p/original/zI3E2a3WYma5w8emI35mgq5Iurx.jpg",
    title: "The Simpsons",
    ontentType: "show",
  },
  {
    id: 100088,
    packdrop_path:
      "https://image.tmdb.org/t/p/original/z7z6zTfEeasEov6Y2ezVOxW5tsb.jpg",
    first_ared: "2023-01-15",
    genres: ["Drama"],
    original_title: "The Last of Us",
    overview:
      "Twenty years after modern civilization has been destroyed, Joel, a hardened survivor, is hired to smuggle Ellie, a 14-year-old girl, out of an oppressive quarantine zone. What starts as a small job soon becomes a brutal, heartbreaking journey, as they both must traverse the United States and depend on each other for survival.",
    poster_path:
      "https://image.tmdb.org/t/p/original/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg",
    title: "The Last of Us",
    ontentType: "show",
  },
  {
    id: 125988,
    packdrop_path:
      "https://image.tmdb.org/t/p/original/n5FPNMJ0eRoiQrKGfUQQRAZeaxg.jpg",
    first_aired: "2023-05-04",
    genres: ["Sci-Fi & Fantasy", "Drama"],
    original_title: "Silo",
    overview:
      "In a ruined and toxic future, a community exists in a giant underground silo that plunges hundreds of stories deep. There, men and women live in a society full of regulations they believe are meant to protect them.",
    poster_path:
      "https://image.tmdb.org/t/p/original/1NxaSn4ver4jIvLeD7YF8cTlZjB.jpg",
    title: "Silo",
    ontentType: "show",
  },
  {
    id: 1416,
    packdrop_path:
      "https://image.tmdb.org/t/p/original/caGVr9Il2gj8bN4ow6qsLm60TxM.jpg",
    first_ared: "2005-03-27",
    genres: ["Drama"],
    original_title: "Grey's Anatomy",
    overview:
      "Follows the personal and professional lives of a group of doctors at Seattle’s Grey Sloan Memorial Hospital.",
    poster_path:
      "https://image.tmdb.org/t/p/original/daSFbrt8QCXV2hSwB0hqYjbj681.jpg",
    title: "Grey's Anatomy",
    ontentType: "show",
  },
  {
    id: 4614,
    packdrop_path:
      "https://image.tmdb.org/t/p/original/5rnL7gIZQvYEKSFTxehqnGcG88u.jpg",
    first_aired: "2003-09-23",
    genres: ["Crie", "Drama", "Action & Adventure"],
    original_title: "NCIS",
    overview:
      "From murder and espionage to terrorism and stolen submarines, a team of special agents investigates any crime that has a shred of evidence connected to Navy and Marine Corps personnel, regardless of rank or position.",
    poster_path:
      "https://image.tmdb.org/t/p/original/2exOHePjOTquUsbThPGhuEjYTyA.jpg",
    title: "NCIS",
    ontentType: "show",
  },
  {
    id: 60735,
    packdrop_path:
      "https://image.tmdb.org/t/p/original/gFkHcIh7iE5G0oVOgpmY8ONQjhl.jpg",
    first_aired: "2014-10-07",
    genres: ["Drama", "Sci-Fi & Fantasy"],
    original_title: "The Flash",
    overview:
      'After a particle accelerator causes a freak storm, CSI Investigator Barry Allen is struck by lightning and falls into a coma. Months later he awakens with the power of super speed, granting him the ability to move through Central City like an unseen guardian angel. Though initially excited by his newfound powers, Barry is shocked to discover he is not the only "meta-human" who was created in the wake of the accelerator explosion -- and not everyone is using their new powers for good. Barry partners with S.T.A.R. Labs and dedicates his life to protect the innocent. For now, only a few close friends and associates know that Barry is literally the fastest man alive, but it won\'t be long before the world learns what Barry Allen has become...The Flash.',
    poster_path:
      "https://image.tmdb.org/t/p/original/rg8N7x27Ef6PvlIiioLStf9ZaIO.jpg",
    title: "The Flash",
    ontentType: "show",
  },
  {
    id: 46952,
    packdrop_path:
      "https://image.tmdb.org/t/p/original/dDPwCyZG8arYwMDoQl0sm4xccCE.jpg",
    first_aired: "2013-09-23",
    genres: ["Draa", "Crime", "Mystery"],
    original_title: "The Blacklist",
    overview:
      'Raymond "Red" Reddington, one of the FBI\'s most wanted fugitives, surrenders in person at FBI Headquarters in Washington, D.C. He claims that he and the FBI have the same interests: bringing down dangerous criminals and terrorists. In the last two decades, he\'s made a list of criminals and terrorists that matter the most but the FBI cannot find because it does not know they exist. Reddington calls this "The Blacklist". Reddington will co-operate, but insists that he will speak only to Elizabeth Keen, a rookie FBI profiler.',
    poster_path:
      "https://image.tmdb.org/t/p/original/htJzeRcYI2ewMm4PTrg98UMXShe.jpg",
    title: "The Blacklist",
    ontentType: "show",
  },
  {
    id: 1434,
    packdrop_path:
      "https://image.tmdb.org/t/p/original/jbTqU6BJMufoMnPSlO4ThrcXs3Y.jpg",
    first_aired: "1999-01-31",
    genres: ["Animation", "Comedy"],
    original_title: "Family Guy",
    overview:
      "Sick, twisted, politically incorrect and Freakin' Sweet animated series featuring the adventures of the dysfunctional Griffin family. Bumbling Peter and long-suffering Lois have three kids. Stewie (a brilliant but sadistic baby bent on killing his mother and taking over the world), Meg (the oldest, and is the most unpopular girl in town) and Chris (the middle kid, he's not very bright but has a passion for movies). The final member of the family is Brian - a talking dog and much more than a pet, he keeps Stewie in check whilst sipping Martinis and sorting through his own life issues.",
    poster_path:
      "https://image.tmdb.org/t/p/original/aLB7psB9N81n5GecHNOudXWW3AI.jpg",
    title: "Family Guy",
    ontentType: "show",
  },
  {
    id: 1622,
    packdrop_path:
      "https://image.tmdb.org/t/p/original/nVRyd8hlg0ZLxBn9RaI7mUMQLnz.jpg",
    first_aired: "2005-09-13",
    genres: ["Draa", "Mystery", "Sci-Fi & Fantasy"],
    original_title: "Supernatural",
    overview:
      "When they were boys, Sam and Dean Winchester lost their mother to a mysterious and demonic supernatural force. Subsequently, their father raised them to be soldiers. He taught them about the paranormal evil that lives in the dark corners and on the back roads of America ... and he taught them how to kill it. Now, the Winchester brothers crisscross the country in their '67 Chevy Impala, battling every kind of supernatural threat they encounter along the way. ",
    poster_path:
      "https://image.tmdb.org/t/p/original/KoYWXbnYuS3b0GyQPkbuexlVK9.jpg",
    title: "Supernatural",
    ontentType: "show",
  },
  {
    id: 63174,
    packdrop_path:
      "https://image.tmdb.org/t/p/original/xZUZ9i6vVayjyhR1vRo9Bjku4h.jpg",
    first_aired: "2016-01-25",
    genres: ["Crime", "Sci-Fi & Fantasy"],
    original_title: "Lucifer",
    overview:
      "Bored and unhappy as the Lord of Hell, Lucifer Morningstar abandoned his throne and retired to Los Angeles, where he has teamed up with LAPD detective Chloe Decker to take down criminals. But the longer he's away from the underworld, the greater the threat that the worst of humanity could escape.",
    poster_path:
      "https://image.tmdb.org/t/p/original/ekZobS8isE6mA53RAiGDG93hBxL.jpg",
    title: "Lucifer",
    ontentType: "show",
  },
  {
    id: 196454,
    packdrop_path:
      "https://image.tmdb.org/t/p/original/dkKEpUCjGEFH5q3GcAGaWG3o2N2.jpg",
    irst_ared: "2023-05-04",
    genres: ["Drama"],
    original_title: "Queen Charlotte: A Bridgerton Story",
    overview:
      "The story of how the young Queen Charlotte’s marriage to King George sparked both a great love story and a societal shift, creating the world of the Ton inherited by the characters in Bridgerton.",
    poster_path:
      "https://image.tmdb.org/t/p/original/eR7btjpvOugivUYSoEsD2iAOYsJ.jpg",
    title: "Queen Charlotte: A Bridgerton Story",
    ontentType: "show",
  },
  {
    id: 71728,
    packdrop_path:
      "https://image.tmdb.org/t/p/original/fXRgyxFxT3SG45fDqUODDRNE9IJ.jpg",
    first_aired: "2017-09-25",
    genres: ["Comedy", "Family"],
    original_title: "Young Sheldon",
    overview:
      "The early life of child genius Sheldon Cooper, later seen in The Big Bang Theory.",
    poster_path:
      "https://image.tmdb.org/t/p/original/MpdROQ5XxQqOMKhJlLUf7PTxIC.jpg",
    title: "Young Sheldon",
  },
  {
    id: 82856,
    packdrop_path:
      "https://image.tmdb.org/t/p/original/6Lw54zxm6BAEKJeGlabyzzR5Juu.jpg",
    first_aired: "219-11-12",
    genres: ["Sci-F & Fantasy", "Action & Adventure", "Drama"],
    original_title: "The Mandalorian",
    overview:
      "After the fall of the Galactic Empire, lawlessness has spread throughout the galaxy. A lone gunfighter makes his way through the outer reaches, earning his keep as a bounty hunter.",
    poster_path:
      "https://image.tmdb.org/t/p/original/eU1i6eHXlzMOlEq0ku1Rzq7Y4wA.jpg",
    title: "The Mandalorian",
  },
  {
    id: 153312,
    packdrop_path:
      "https://image.tmdb.org/t/p/original/mNHRGO1gFpR2CYZdANe72kcKq7G.jpg",
    first_aired: "2022-11-13",
    genres: ["Crime", "Drama"],
    original_title: "Tulsa King",
    overview:
      "Just after he is released from prison after 25 years, New York mafia capo Dwight “The General” Manfredi is unceremoniously exiled by his boss to set up shop in Tulsa, Okla. Realizing that his mob family may not have his best interests in mind, Dwight slowly builds a “crew” from a group of unlikely characters, to help him establish a new criminal empire in a place that to him might as well be another planet.",
    poster_path:
      "https://image.tmdb.org/t/p/original/fwTv3RPRAIy0maOMns5eYRRwnDk.jpg",
    title: "Tulsa King",
  },
  {
    id: 119051,
    packdrop_path:
      "https://image.tmdb.org/t/p/original/iHSwvRVsRyxpX7FE7GbviaDvgGZ.jpg",
    first_aired: "222-11-23",
    genres: ["Sci-F & Fantasy", "Mystery", "Comedy"],
    original_title: "Wednesday",
    overview:
      "Wednesday Addams is sent to Nevermore Academy, a bizarre boarding school where she attempts to master her psychic powers, stop a monstrous killing spree of the town citizens, and solve the supernatural mystery that affected her family 25 years ago — all while navigating her new relationships.",
    poster_path:
      "https://image.tmdb.org/t/p/original/9PFonBhy4cQy7Jz20NpMygczOkv.jpg",
    title: "Wednesday",
  },
  {
    id: 65334,
    packdrop_path:
      "https://image.tmdb.org/t/p/original/ogMd4e3A0uSNwZADzgC23zCByoi.jpg",
    first_aired: "215-10-19",
    genres: ["Actio & Adventure", "Animation", "Family"],
    original_title: "Miraculous, les aventures de Ladybug et Chat Noir",
    overview:
      "Normal high school kids by day, protectors of Paris by night! Miraculous follows the heroic adventures of Marinette and Adrien as they transform into Ladybug and Cat Noir and set out to capture akumas, creatures responsible for turning the people of Paris into villains. But neither hero knows the other’s true identity – or that they’re classmates!",
    poster_path:
      "https://image.tmdb.org/t/p/original/psDcRgUX38cIeGeADwLRPyO7SYC.jpg",
    title: "Miraculous: Tales of Ladybug & Cat Noir",
  },
  {
    id: 223313,
    packdrop_path:
      "https://image.tmdb.org/t/p/original/dpaaxgmIe0cCId6CVIAOfNqkYm4.jpg",
    first_aired: "2023-04-13",
    genres: ["Drama", "Mystery"],
    original_title: "Obsession",
    overview:
      "A respected London surgeon's affair with his son's fiancée turns into an erotic infatuation that threatens to change their lives forever.",
    poster_path:
      "https://image.tmdb.org/t/p/original/8nQmxCYvidrCMxYCPdhuls94cl9.jpg",
    title: "Obsession",
  },
  {
    id: 71712,
    packdrop_path:
      "https://image.tmdb.org/t/p/original/xXRsKNJHTOGrs5wfYAxkbM2RiyT.jpg",
    irst_ared: "2017-09-25",
    genres: ["Drama"],
    original_title: "The Good Doctor",
    overview:
      "Shaun Murphy, a young surgeon with autism and savant syndrome, relocates from a quiet country life to join a prestigious hospital's surgical unit. Unable to personally connect with those around him, Shaun uses his extraordinary medical gifts to save lives and challenge the skepticism of his colleagues.",
    poster_path:
      "https://image.tmdb.org/t/p/original/luhKkdD80qe62fwop6sdrXK9jUT.jpg",
    title: "The Good Doctor",
  },
  {
    id: 63333,
    packdrop_path:
      "https://image.tmdb.org/t/p/original/uCqXSfHymdbDMsFx8t0u0OPSuve.jpg",
    first_aired: "215-10-10",
    genres: ["Actio & Adventure", "Drama", "War"],
    original_title: "The Last Kingdom",
    overview:
      "A show of heroic deeds and epic battles with a thematic depth that embraces politics, religion, warfare, courage, love, loyalty and our universal search for identity. Combining real historical figures and events with fictional characters, it is the story of how a people combined their strength under one of the most iconic kings of history in order to reclaim their land for themselves and build a place they call home.",
    poster_path:
      "https://image.tmdb.org/t/p/original/8eJf0hxgIhE6QSxbtuNCekTddy1.jpg",
    title: "The Last Kingdom",
  },
  {
    id: 44217,
    packdrop_path:
      "https://image.tmdb.org/t/p/original/lHe8iwM4Cdm6RSEiara4PN8ZcBd.jpg",
    first_aired: "213-03-03",
    genres: ["Actio & Adventure", "Drama", "War"],
    original_title: "Vikings",
    overview:
      "The adventures of Ragnar Lothbrok, the greatest hero of his age. The series tells the sagas of Ragnar's band of Viking brothers and his family, as he rises to become King of the Viking tribes. As well as being a fearless warrior, Ragnar embodies the Norse traditions of devotion to the gods. Legend has it that he was a direct descendant of Odin, the god of war and warriors.",
    poster_path:
      "https://image.tmdb.org/t/p/original/bQLrHIRNEkE3PdIWQrZHynQZazu.jpg",
    title: "Vikings",
  },
  {
    id: 34307,
    packdrop_path:
      "https://image.tmdb.org/t/p/original/5s9XHTB9SLPdg3mNU6BlSLnZ9Qq.jpg",
    first_aired: "2011-01-09",
    genres: ["Drama", "Comedy"],
    original_title: "Shameless",
    overview:
      "Chicagoan Frank Gallagher is the proud single dad of six smart, industrious, independent kids, who without him would be... perhaps better off. When Frank's not at the bar spending what little money they have, he's passed out on the floor. But the kids have found ways to grow up in spite of him. They may not be like any family you know, but they make no apologies for being exactly who they are.",
    poster_path:
      "https://image.tmdb.org/t/p/original/9akij7PqZ1g6zl42DQQTtL9CTSb.jpg",
    title: "Shameless",
  },
  {
    id: 1431,
    packdrop_path:
      "https://image.tmdb.org/t/p/original/cvlLBcQWpO9X21jDHhgPJnE2aVq.jpg",
    first_aired: "2000-10-06",
    genres: ["Crie", "Drama", "Mystery"],
    original_title: "CSI: Crime Scene Investigation",
    overview:
      "A Las Vegas team of forensic investigators are trained to solve criminal cases by scouring the crime scene, collecting irrefutable evidence and finding the missing pieces that solve the mystery.",
    poster_path:
      "https://image.tmdb.org/t/p/original/9XecVOLLkbGBNnpF2PvP8vQBmww.jpg",
    title: "CSI: Crime Scene Investigation",
  },
  {
    id: 1400,
    packdrop_path:
      "https://image.tmdb.org/t/p/original/tMRdEsMg9MyXAkcufK9YJEeIaNW.jpg",
    irst_ared: "1989-07-05",
    genre: ["Comedy"],
    original_title: "Seinfeld",
    overview:
      "A stand-up comedian and his three offbeat friends weather the pitfalls and payoffs of life in New York City in the '90s. It's a show about nothing.",
    poster_path:
      "https://image.tmdb.org/t/p/original/aCw8ONfyz3AhngVQa1E2Ss4KSUQ.jpg",
    title: "Seinfeld",
  },
  {
    id: 44006,
    packdrop_path:
      "https://image.tmdb.org/t/p/original/a1axm2xRYGB35X406AMI51IrhYp.jpg",
    irst_ared: "2012-10-10",
    genres: ["Drama"],
    original_title: "Chicago Fire",
    overview:
      "An edge-of-your-seat view into the lives of everyday heroes committed to one of America's noblest professions. For the firefighters, rescue squad and paramedics of Chicago Firehouse 51, no occupation is more stressful or dangerous, yet so rewarding and exhilarating. These courageous men and women are among the elite who forge headfirst into danger when everyone else is running the other way and whose actions make the difference between life and death.",
    poster_path:
      "https://image.tmdb.org/t/p/original/iiI1YU8akLYWdWuX1qHuMYPvSHC.jpg",
    title: "Chicago Fire",
  },
  {
    id: 37680,
    packdrop_path:
      "https://image.tmdb.org/t/p/original/or0E36KfzJYZwqXeiCfm1JgepKF.jpg",
    first_ared: "2011-06-23",
    genres: ["Drama"],
    original_title: "Suits",
    overview:
      "While running from a drug deal gone bad, Mike Ross, a brilliant young college-dropout, slips into a job interview with one of New York City's best legal closers, Harvey Specter. Tired of cookie-cutter law school grads, Harvey takes a gamble by hiring Mike on the spot after he recognizes his raw talent and photographic memory.",
    poster_path:
      "https://image.tmdb.org/t/p/original/vQiryp6LioFxQThywxbC6TuoDjy.jpg",
    title: "Suits",
  },
  {
    id: 1399,
    packdrop_path:
      "https://image.tmdb.org/t/p/original/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg",
    first_aired: "211-04-17",
    genres: ["Sci-F & Fantasy", "Drama", "Action & Adventure"],
    original_title: "Game of Thrones",
    overview:
      "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
    poster_path:
      "https://image.tmdb.org/t/p/original/7WUHnWGx5OO145IRxPDUkQSh4C7.jpg",
    title: "Game of Thrones",
  },
  {
    id: 4057,
    ckdrop_path:
      "https://image.tmdb.org/t/p/original/65Y6PweSvQ1OOFBzStybjipURRP.jpg",
    first_aired: "2005-09-22",
    genres: ["Crie", "Drama", "Mystery"],
    original_title: "Criminal Minds",
    overview:
      "An elite team of FBI profilers analyze the country's most twisted criminal minds, anticipating their next moves before they strike again. The Behavioral Analysis Unit's most experienced agent is David Rossi, a founding member of the BAU who returns to help the team solve new cases.",
    poster_path:
      "https://image.tmdb.org/t/p/original/7TCwgX7oQKxcWYEhSPRmaHe6ULN.jpg",
    title: "Criminal Minds",
  },
  {
    id: 97951,
    packdrop_path:
      "https://image.tmdb.org/t/p/original/gQxaF79LUTtopdYHsuS8lUr9rvF.jpg",
    first_aired: "2021-11-14",
    genres: ["Drama", "Crime"],
    original_title: "Mayor of Kingstown",
    overview:
      "In a small Michigan town where the business of incarceration is the only thriving industry, the McClusky family are the power brokers between the police, criminals, inmates, prison guards and politicians in a city completely dependent on prisons and the prisoners they contain.",
    poster_path:
      "https://image.tmdb.org/t/p/original/86OUOPulMiM8rjrQSt4KMev7UAa.jpg",
    title: "Mayor of Kingstown",
  },
  {
    id: 60574,
    packdrop_path:
      "https://image.tmdb.org/t/p/original/wiE9doxiLwq3WCGamDIOb2PqBqc.jpg",
    first_aired: "2013-09-12",
    genres: ["Drama", "Crime"],
    original_title: "Peaky Blinders",
    overview:
      "A gangster family epic set in 1919 Birmingham, England and centered on a gang who sew razor blades in the peaks of their caps, and their fierce boss Tommy Shelby, who means to move up in the world.",
    poster_path:
      "https://image.tmdb.org/t/p/original/vUUqzWa2LnHIVqkaKVlVGkVcZIW.jpg",
    title: "Peaky Blinders",
  },
  {
    id: 73586,
    packdrop_path:
      "https://image.tmdb.org/t/p/original/2Erj4Oav9EHAtqLI354VM7ULDqu.jpg",
    first_aired: "2018-06-20",
    genres: ["Western", "Drama"],
    original_title: "Yellowstone",
    overview:
      "Follow the violent world of the Dutton family, who controls the largest contiguous ranch in the United States. Led by their patriarch John Dutton, the family defends their property against constant attack by land developers, an Indian reservation, and America’s first National Park.",
    poster_path:
      "https://image.tmdb.org/t/p/original/peNC0eyc3TQJa6x4TdKcBPNP4t0.jpg",
    title: "Yellowstone",
  },
  {
    id: 1911,
    packdrop_path:
      "https://image.tmdb.org/t/p/original/e9n87p3Ax67spq3eUgLB6rjIEow.jpg",
    first_aired: "2005-09-13",
    genres: ["Crime", "Drama"],
    original_title: "Bones",
    overview:
      "Dr. Temperance Brennan and her colleagues at the Jeffersonian's Medico-Legal Lab assist Special Agent Seeley Booth with murder investigations when the remains are so badly decomposed, burned or destroyed that the standard identification methods are useless.",
    poster_path:
      "https://image.tmdb.org/t/p/original/eyTu5c8LniVciRZIOSHTvvkkgJa.jpg",
    title: "Bones",
  },
  {
    id: 32692,
    packdrop_path:
      "https://image.tmdb.org/t/p/original/3a5k2ZuLMNhpMEZIq9hf3lCSOS.jpg",
    first_aired: "2010-09-24",
    genres: ["Drama", "Crime"],
    original_title: "Blue Bloods",
    overview:
      "A drama about a multi-generational family of cops dedicated to New York City law enforcement. Frank Reagan is the New York Police Commissioner and heads both the police force and the Reagan brood. He runs his department as diplomatically as he runs his family, even when dealing with the politics that plagued his unapologetically bold father, Henry, during his stint as Chief.",
    poster_path:
      "https://image.tmdb.org/t/p/original/ceqomvL0e1jGkJAPVWFlq2hGl7i.jpg",
    title: "Blue Bloods",
  },
  {
    id: 57532,
    packdrop_path:
      "https://image.tmdb.org/t/p/original/7OrV2aAH5Yp7hA9zCCvUloLvZtl.jpg",
    first_aired: "2013-08-12",
    genres: ["Animation", "Family"],
    original_title: "PAW Patrol",
    overview:
      "PAW Patrol is a CG action-adventure for old children and preschool series starring a pack of six heroic puppies led by a tech-savvy 10-year-old boy named Ryder.",
    poster_path:
      "https://image.tmdb.org/t/p/original/8HXkgUBO5OF8ZK9XbY69RM4S5rv.jpg",
    title: "PAW Patrol",
  },
  {
    id: 549,
    packdrop_path:
      "https://image.tmdb.org/t/p/original/oOce9hLMVFubjAJliau4kiSNPnW.jpg",
    first_aired: "1990-09-13",
    genres: ["Crime", "Drama"],
    original_title: "Law & Order",
    overview:
      "In cases ripped from the headlines, police investigate serious and often deadly crimes, weighing the evidence and questioning the suspects until someone is taken into custody. The district attorney's office then builds a case to convict the perpetrator by proving the person guilty beyond a reasonable doubt. Working together, these expert teams navigate all sides of the complex criminal justice system to make New York a safer place.",
    poster_path:
      "https://image.tmdb.org/t/p/original/77OPlbsvX3pzoFbyfpcE3GXMCod.jpg",
    title: "Law & Order",
  },
  {
    id: 1408,
    packdrop_path:
      "https://image.tmdb.org/t/p/original/r9t9lblyPfudl0LV0Ujg1nXdKyW.jpg",
    first_aired: "2004-11-16",
    genres: ["Drama", "Mystery"],
    original_title: "House",
    overview:
      "Dr. Gregory House, a drug-addicted, unconventional, misanthropic medical genius, leads a team of diagnosticians at the fictional Princeton–Plainsboro Teaching Hospital in New Jersey.",
    poster_path:
      "https://image.tmdb.org/t/p/original/5rIQ3pTjWdZjNUJSJxn1T8MIvoG.jpg",
    title: "House",
  },
  {
    id: 1402,
    packdrop_path:
      "https://image.tmdb.org/t/p/original/wvdWb5kTQipdMDqCclC6Y3zr4j3.jpg",
    first_aired: "210-10-31",
    genres: ["Actio & Adventure", "Drama", "Sci-Fi & Fantasy"],
    original_title: "The Walking Dead",
    overview:
      "Sheriff's deputy Rick Grimes awakens from a coma to find a post-apocalyptic world dominated by flesh-eating zombies. He sets out to find his family and encounters many other survivors along the way.",
    poster_path:
      "https://image.tmdb.org/t/p/original/xf9wuDcqlUPWABZNeDKPbZUjWx0.jpg",
    title: "The Walking Dead",
  },
  {
    id: 2691,
    packdrop_path:
      "https://image.tmdb.org/t/p/original/5SQaNc5loVTrx1cDBnB72ewXLPp.jpg",
    first_aired: "2003-09-22",
    genres: ["Comedy", "Drama"],
    original_title: "Two and a Half Men",
    overview:
      "A hedonistic jingle writer's free-wheeling life comes to an abrupt halt when his brother and 10-year-old nephew move into his beach-front house.",
    poster_path:
      "https://image.tmdb.org/t/p/original/A9QDK4OWpv41W27kCv0LXe30k9S.jpg",
    title: "Two and a Half Men",
  },
  {
    id: 12971,
    packdrop_path:
      "https://image.tmdb.org/t/p/original/ydf1CeiBLfdxiyNTpskM0802TKl.jpg",
    first_aired: "189-04-26",
    genres: ["Animaion", "Sci-Fi & Fantasy", "Action & Adventure"],
    original_title: "ドラゴンボールゼット",
    overview:
      "The adventures of Earth's martial arts defender, Son Goku, continue with a new family and the revelation of his alien origins. Now Goku and his allies must defend the planet from an onslaught of new extraterrestrial enemies.",
    poster_path:
      "https://image.tmdb.org/t/p/original/6VKOfL6ihwTiB5Vibq6QTfzhxA6.jpg",
    title: "Dragon Ball Z",
  },
  {
    id: 1433,
    packdrop_path:
      "https://image.tmdb.org/t/p/original/7xIQL3eyNmQjZTJjzlsmzRUjAEx.jpg",
    first_aired: "2005-02-06",
    genres: ["Animation", "Comedy"],
    original_title: "American Dad!",
    overview:
      "The series focuses on an eccentric motley crew that is the Smith family and their three housemates: Father, husband, and breadwinner Stan Smith; his better half housewife, Francine Smith; their college-aged daughter, Hayley Smith; and their high-school-aged son, Steve Smith. Outside of the Smith family, there are three additional main characters, including Hayley's boyfriend turned husband, Jeff Fischer; the family's man-in-a-goldfish-body pet, Klaus; and most notably the family's zany alien, Roger, who is \"full of masquerades, brazenness, and shocking antics.\"",
    poster_path:
      "https://image.tmdb.org/t/p/original/8bSEmNdnEBOCdKzCs3FKcSguUz.jpg",
    title: "American Dad!",
  },
  {
    id: 60625,
    packdrop_path:
      "https://image.tmdb.org/t/p/original/uGy4DCmM33I7l86W7iCskNkvmLD.jpg",
    irt_aired: "2013-12-02",
    genres: ["Animation", "Comey", "Sci-Fi & Fantasy", "Action & Adventure"],
    original_title: "Rick and Morty",
    overview:
      "Rick is a mentally-unbalanced but scientifically gifted old man who has recently reconnected with his family. He spends most of his time involving his young grandson Morty in dangerous, outlandish adventures throughout space and alternate universes. Compounded with Morty's already unstable family life, these events cause Morty much distress at home and school.",
    poster_path:
      "https://image.tmdb.org/t/p/original/cvhNj9eoRBe5SxjCbQTkh05UP5K.jpg",
    title: "Rick and Morty",
  },
  {
    id: 59941,
    packdrop_path:
      "https://image.tmdb.org/t/p/original/xl1wGwaPZInJo1JAnpKqnFozWBE.jpg",
    first_aired: "2014-02-17",
    genres: ["Comedy", "Talk"],
    original_title: "The Tonight Show Starring Jimmy Fallon",
    overview:
      "After Jay Leno's second retirement from the program, Jimmy Fallon stepped in as his permanent replacement. After 42 years in Los Angeles the program was brought back to New York.",
    poster_path:
      "https://image.tmdb.org/t/p/original/2ItOtzcGlBT39b3xYkmYi82pp9r.jpg",
    title: "The Tonight Show Starring Jimmy Fallon",
    contentType: "show",
  },
];
let UPCOMING = document.querySelectorAll(".UPCOMING .box-img ");
let text1 = document.querySelectorAll(".UPCOMING h3 ");

let SUGGESTIONS = document.querySelectorAll(".SUGGESTIONS  .box-img");
let text2 = document.querySelectorAll(".SUGGESTIONS h3 ");

let TOPRATE = document.querySelectorAll(".TOPRATE .box-img");
let text3 = document.querySelectorAll(".TOPRATE h3 ");

let MOVIES = document.querySelectorAll(".MOVIES .box-img");
let text4 = document.querySelectorAll(".MOVIES h3 ");


for (i = 0; i < UPCOMING.length; i++) {
  text1[i].textContent = upcoming[i].title;
  SUGGESTIONS[i].children[0].loading = "lazy";
  UPCOMING[i].children[0].src =
    "https://image.tmdb.org/t/p/original" + upcoming[i].poster_path;
}
for (i = 0; i < SUGGESTIONS.length-1; i++) {
  text2[i].textContent = suggestion[i].title;
  SUGGESTIONS[i].children[0].src =
    "https://image.tmdb.org/t/p/original" + suggestion[i].poster_path;
  SUGGESTIONS[i].children[0].loading = "lazy";
}
for (i = 0; i < TOPRATE.length; i++) {
  text3[i].textContent = toprating[i].title;
  TOPRATE[i].children[0].src ="https://image.tmdb.org/t/p/original" + toprating[i].poster_path;
}
for (i = 0; i < MOVIES.length; i++) {
  text4[i].textContent = movies[i].title;
  MOVIES[i].children[0].src = movies[i].poster_path;
}